FALLACIES = [
    {
        'id': 'god-of-gaps',
        'name': 'God of the Gaps',
        'icon': '🕳️',
        'color': '#a855f7',
        'definition': 'Inserting God as the explanation wherever science currently has no answer — "We don\'t know X, therefore God did X."',
        'why_wrong': 'This argument does not provide positive evidence for God — it only points to a gap in scientific knowledge. Historically, every gap has been filled: lightning (Zeus → atmospheric electricity), disease (punishment/demons → germ theory), mental illness (possession → neuroscience), the origin of species (special creation → evolution). The God of the Gaps shrinks with every scientific advance. A God who can only be found where knowledge ends is a God of decreasing territory.',
        'example': '"Scientists don\'t know how the first life arose — therefore God created it."',
        'rebuttal': '"We don\'t know yet" is an honest scientific position. "Therefore God" is an unjustified leap. The history of science is the history of once-divine phenomena receiving natural explanations.',
        'also_known_as': 'Argument from Ignorance (Ad Ignorantiam)',
    },
    {
        'id': 'special-pleading',
        'name': 'Special Pleading',
        'icon': '🛡️',
        'color': '#f97316',
        'definition': 'Applying a rule to everything except God, without justification for the exception.',
        'why_wrong': 'Special pleading is logically inconsistent. If the rule "everything has a cause" applies to the universe, it applies to God too. If the rule "complex things require a designer" applies to the universe, it applies to God too. Exempting God from every rule that was introduced to require God is circular reasoning.',
        'example': '"Everything that exists has a cause — therefore the universe has a cause (God). But God doesn\'t need a cause because He is eternal/uncaused."',
        'rebuttal': 'If causeless existence is possible for God, it is equally possible for the universe. If God can be eternal and self-explanatory, so can the quantum vacuum or the multiverse — with the advantage that these are physically defined concepts.',
        'also_known_as': 'Moving the Goalposts; Ad Hoc Exemption',
    },
    {
        'id': 'false-dilemma',
        'name': 'False Dilemma (False Dichotomy)',
        'icon': '⚖️',
        'color': '#00d4ff',
        'definition': 'Presenting two options as the only possibilities when others exist.',
        'why_wrong': 'Real questions usually have more than two possible answers. Presenting only two forces a choice between artificially limited options.',
        'example': '"Either the universe was designed by God, or everything happened by pure random chance. Random chance is impossible — therefore God." (Pascal\'s Wager is another example: "Either believe in God or risk hell." This ignores the thousands of other gods, agnosticism, and the possibility that no god punishes honest non-belief.)',
        'rebuttal': 'The false dilemma between "God or random chance" ignores natural selection (non-random), physical law (deterministic), quantum probability (inherent but non-arbitrary), and cosmological models. Evolution is specifically NOT random chance — it is non-random selection of random variation.',
        'also_known_as': 'Either/Or Fallacy; Black-and-White Thinking',
    },
    {
        'id': 'circular-reasoning',
        'name': 'Circular Reasoning (Begging the Question)',
        'icon': '🔄',
        'color': '#22c55e',
        'definition': 'Using the conclusion as one of the premises — the argument only works if you already accept what it\'s trying to prove.',
        'why_wrong': 'Circular arguments have the form "X is true because X is true." They cannot produce new knowledge because the conclusion adds nothing beyond the premises.',
        'example': '"The Bible is the word of God. We know this because the Bible says so. The Bible is accurate because it is the word of God." Or: "God exists because the universe needs a creator. How do we know the universe needs a creator? Because God created it, and God doesn\'t do things without purpose."',
        'rebuttal': 'The claim that scripture is reliable cannot be validated by the scripture itself. An independent, external standard of verification is required. This is exactly what archaeology, textual criticism, and comparative history provide — and they consistently find the historical claims of scripture unverified.',
        'also_known_as': 'Petitio Principii; Circular Argument',
    },
    {
        'id': 'appeal-to-authority',
        'name': 'Appeal to Authority (Irrelevant Authority)',
        'icon': '👑',
        'color': '#fbbf24',
        'definition': 'Treating a claim as true because an authority figure said it — especially when the authority is outside their domain of expertise.',
        'why_wrong': 'Authority is relevant only within a domain of expertise. A Nobel Prize-winning physicist has no greater theological authority than a plumber. A theologian has no special authority on cosmological origins. The claim must stand on evidence and argument, not credentials.',
        'example': '"Einstein believed in God." (He didn\'t — he used "God" as a poetic metaphor for the universe\'s order.) "Francis Collins, the director of the NIH, is a Christian — therefore religion is compatible with science." (Collins\'s religious beliefs don\'t validate the resurrection any more than his genetics expertise validates transubstantiation.)',
        'rebuttal': 'Scientific consensus is not an appeal to authority fallacy — it is the accumulated weight of independently replicated evidence. The difference: "Scientists agree on evolution" cites a convergent body of evidence; "Einstein said God doesn\'t play dice" cites one person\'s personal belief outside their relevant expertise.',
        'also_known_as': 'Argumentum Ad Verecundiam',
    },
    {
        'id': 'no-true-scotsman',
        'name': 'No True Scotsman',
        'icon': '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
        'color': '#94a3b8',
        'definition': 'Redefining a category to exclude embarrassing examples, then claiming the original claim still holds.',
        'why_wrong': 'By constantly redefining who counts as a "real" member of a group, any claim about that group becomes unfalsifiable. This moves the goalposts to avoid refutation rather than engaging with evidence.',
        'example': '"No true Christian would support the Crusades." "No true Muslim endorses terrorism." "No true religious person abused children." When confronted with religious violence, the response is always: "Those weren\'t real [religion] — real [religion] would never do that." This exempts religion from accountability for any actions done in its name.',
        'rebuttal': 'The Crusades were launched by the Pope with explicit theological justification and promises of indulgences. The Inquisition was an official Church institution. ISIS explicitly quotes Quranic verses. If official representatives of a religion, acting in its name, using its scripture, don\'t count as "real" adherents, the category is empty.',
        'also_known_as': 'Moving the Goalposts; Ad Hoc Rescue',
    },
    {
        'id': 'appeal-to-tradition',
        'name': 'Appeal to Tradition',
        'icon': '📯',
        'color': '#a855f7',
        'definition': 'Arguing that something must be correct or good because it has been believed or practiced for a long time.',
        'why_wrong': 'Longevity tells us nothing about truth. Slavery was practiced for millennia. Geocentrism was the consensus for thousands of years. Blood-letting as medicine was practiced for over 2,000 years. Duration of belief does not produce evidence.',
        'example': '"Religion has been part of human culture for hundreds of thousands of years — there must be something to it." "Our ancestors believed in God — are you claiming they were all wrong?"',
        'rebuttal': 'Cognitive science of religion explains the longevity of religious belief as a predictable by-product of evolved cognitive systems (agency detection, pattern-seeking, minimally counterintuitive concepts) — without requiring any of the beliefs to be true. The fact that a belief spreads and persists in human populations tells us about human psychology, not about external reality.',
        'also_known_as': 'Argumentum Ad Antiquitatem; Appeal to Common Practice',
    },
    {
        'id': 'argument-from-incredulity',
        'name': 'Argument from Incredulity',
        'icon': '😤',
        'color': '#f97316',
        'definition': 'Claiming something must be false (or that God must be the explanation) because the person cannot imagine how it could be true (or could have a natural cause).',
        'why_wrong': 'Personal failure to imagine an explanation is not evidence that no explanation exists. This is a cognitive limitation, not a logical argument. The universe is not obligated to be comprehensible to human intuition.',
        'example': '"I cannot imagine how the eye could have evolved step by step — it must have been designed." "The odds of life arising from chemistry are astronomically small — it can\'t have happened by chance." "I can\'t conceive of the universe existing without a cause — therefore it had a cause (God)."',
        'rebuttal': 'Darwin showed precisely how the eye could evolve in gradual steps — from a light-sensitive patch to a complex camera eye, with every intermediate stage functional and selected for. Inability to imagine the mechanism before having the explanation does not establish that the mechanism doesn\'t exist. This argument stopped working for lightning, disease, life\'s origin, and stellar formation — it will stop working for consciousness too.',
        'also_known_as': 'Argument from Personal Incredulity; "I can\'t imagine it, therefore impossible"',
    },
    {
        'id': 'straw-man',
        'name': 'Straw Man',
        'icon': '🎯',
        'color': '#00d4ff',
        'definition': 'Misrepresenting or exaggerating an opponent\'s argument to make it easier to attack, instead of addressing the actual claim.',
        'why_wrong': 'Attacking a distorted version of an argument is not a refutation of the actual position. The straw man creates the illusion of victory while avoiding engagement with the real challenge. It is particularly common in religious discourse because the actual scientific and philosophical challenges to theism are difficult to answer directly.',
        'example': '"Atheists believe life arose from nothing and the universe is totally random — therefore atheism makes no sense." (Atheism claims no such thing. The actual position is that natural processes with scientifically studied mechanisms produced life.) "Evolutionists think we descended from monkeys." (Evolution says humans and apes share a common ancestor — both have continued evolving since.)',
        'rebuttal': '"That\'s not what I said. My actual position is [restate clearly]. Please address that argument." Identifying and naming the straw man is usually sufficient — it shifts the burden back to your opponent to engage with your real claim rather than the caricature.',
        'also_known_as': 'Misrepresentation; Weak Man Argument',
    },
    {
        'id': 'ad-hominem',
        'name': 'Ad Hominem (Personal Attack)',
        'icon': '👊',
        'color': '#a855f7',
        'definition': 'Attacking the person making an argument rather than the argument itself — dismissing a claim because of who made it, rather than evaluating its content.',
        'why_wrong': 'The truth of a claim is independent of the characteristics of the person making it. A logically valid argument made by a terrible person is still a logically valid argument. A false argument made by a saint is still a false argument. Ad hominem diverts attention from the substance of the debate.',
        'example': '"You\'re only an atheist because you\'re angry at God, or because your father abandoned you." "Richard Dawkins is arrogant — therefore evolution is wrong." "Sam Harris supported drone strikes — therefore his arguments about religion are invalid." None of these address the actual arguments being made.',
        'rebuttal': '"My personal characteristics are irrelevant to whether the argument is correct. Please address the specific claim I made." Note: there IS a valid form of ad hominem when addressing someone\'s credibility on a question of testimony (eyewitness reliability), but not when evaluating a logical or empirical argument.',
        'also_known_as': 'Personal Attack; Genetic Fallacy (when attacking the origin of a belief)',
    },
    {
        'id': 'slippery-slope',
        'name': 'Slippery Slope',
        'icon': '⛷️',
        'color': '#22c55e',
        'definition': 'Claiming that one step will inevitably lead to a chain of extreme and undesirable consequences, without providing evidence for the claimed causal chain.',
        'why_wrong': 'The argument assumes the first step will inevitably lead to the extreme conclusion without demonstrating the mechanism. Most "slippery slopes" do not materialise. The strength of the argument depends entirely on how probable each step is — which is usually not demonstrated at all.',
        'example': '"If we teach evolution in schools, children will believe they are just animals and society will collapse into immorality." "If atheism spreads, all ethics will disappear and we\'ll have chaos." "If we allow same-sex marriage, next people will want to marry animals."',
        'rebuttal': 'Identify the specific causal mechanism claimed for each step in the slope. Cite empirical evidence: countries with the most secular populations (Scandinavia) have the most stable, ethical, and cooperative societies — the predicted slope has not occurred where we can check. Demand evidence for the chain of causation, not just the assertion of it.',
        'also_known_as': 'Camel\'s Nose; Thin End of the Wedge',
    },
    {
        'id': 'tu-quoque',
        'name': 'Tu Quoque (Whataboutism)',
        'icon': '🔁',
        'color': '#fbbf24',
        'definition': 'Deflecting a criticism by pointing to the opponent\'s alleged similar faults, rather than addressing the original criticism.',
        'why_wrong': 'Even if the opponent is guilty of the same fault, this does not address whether the original criticism is correct. Two wrongs do not make a right. The truth of a claim is independent of whether the person challenging it is also guilty of something.',
        'example': '"You criticise Islamic violence, but what about the Crusades?" "You say religion causes harm, but Stalin\'s secular regime killed people too." (Both may be true, but neither addresses the specific claim being made — they redirect to a different topic entirely.)',
        'rebuttal': '"You may be correct about that separate issue, but it doesn\'t address my specific claim, which is [restate claim]. We can discuss that other matter separately." Keep the conversation focused on one claim at a time and refuse to let it be derailed.',
        'also_known_as': 'Two Wrongs Make a Right; Whataboutism; Appeal to Hypocrisy',
    },
]

SCRIPTURE_VS_SCIENCE = [
    {
        'id': 'age-of-earth',
        'icon': '🌍',
        'claim': 'The Earth is approximately 6,000 years old (derived from biblical genealogies by Archbishop Ussher in 1650: created October 23, 4004 BCE).',
        'what_science_says': 'The Earth is 4.54 ± 0.05 billion years old, determined by uranium-lead radiometric dating of zircon crystals (oldest found: 4.4 billion years), lead-lead dating of meteorites (which formed with the solar system), and confirmed independently by stellar astrophysics (the Sun\'s age), lunar sample dating, and the geologic column.',
        'error': '750,000×',
        'category': 'geology',
        'sources': 'Canyon Diablo meteorite Pb-Pb dating; Jack Hills zircons (4.4 Ga); multiple independent radiometric methods',
    },
    {
        'id': 'age-of-universe',
        'icon': '🔭',
        'claim': 'The universe was created in 6 days, ~6,000 years ago.',
        'what_science_says': 'The universe is 13.799 ± 0.021 billion years old, measured by the Planck satellite\'s mapping of the cosmic microwave background (CMB). This is confirmed independently by the Hubble constant, stellar ages (the oldest stars are ~13.2 billion years), and the ages of the oldest globular clusters.',
        'error': '2.3 million×',
        'category': 'cosmology',
        'sources': 'Planck Collaboration (2018); CMB angular power spectrum; Hubble constant measurements',
    },
    {
        'id': 'origin-of-species',
        'icon': '🧬',
        'claim': 'All species were created separately in their current forms by God, within a 6-day creation period.',
        'what_science_says': 'All species are descended from a common ancestor, with the last universal common ancestor (LUCA) living approximately 3.5–3.8 billion years ago. The relationship between species is described by an evolutionary tree confirmed by the fossil record, comparative anatomy, molecular genetics (DNA sequences), and direct observation of speciation events.',
        'error': 'Fundamentally wrong — no species was created in its current form',
        'category': 'biology',
        'sources': 'Darwin (1859); Modern Synthesis; genomic sequencing; fossil record; LUCA molecular phylogeny',
    },
    {
        'id': 'global-flood',
        'icon': '🌊',
        'claim': 'A global flood covered the entire Earth including the highest mountains (~2,350 BCE by standard biblical chronology), killing all land life except those on Noah\'s Ark.',
        'what_science_says': 'No global flood occurred at any point in human history. Ice cores (Antarctic Vostok core: 800,000 years of continuous layering), deep-sea sediment cores, cave stalagmites, the global geologic column, and dendrochronology (tree ring records extending continuously through the supposed flood date) all show uninterrupted records. Egyptian, Chinese, and Mesopotamian civilisations were continuously active through the supposed flood date.',
        'error': 'No geological, archaeological, or climatological evidence exists',
        'category': 'geology',
        'sources': 'Antarctic ice cores (EPICA); global stratigraphy; Egyptian, Chinese continuous historical records through 2350 BCE',
    },
    {
        'id': 'geocentrism',
        'icon': '🪐',
        'claim': 'The Earth is the centre of the universe (geocentrism — Psalms 93:1, 104:5, Joshua 10:12–13 where the Sun "stood still" implying it normally moves).',
        'what_science_says': 'The Earth orbits the Sun at ~150 million km. The Sun orbits the Milky Way\'s centre. The Milky Way is one of ~2 trillion galaxies. There is no centre to the observable universe. Earth occupies no special position in the cosmos.',
        'error': 'The Earth moves at 107,000 km/h around the Sun it was said to orbit',
        'category': 'astronomy',
        'sources': 'Copernicus (1543); Galileo (1610); Newton (1687); modern GPS confirming relativistic orbital mechanics',
    },
    {
        'id': 'human-origin',
        'icon': '🧑',
        'claim': 'Humanity was created by God from dust (or clay), with women subsequently created from a man\'s rib. All humans are descended from a single pair (Adam and Eve).',
        'what_science_says': 'Homo sapiens evolved gradually from earlier hominid ancestors over approximately 6–8 million years, with anatomically modern humans emerging ~300,000 years ago in Africa. Population genetics demonstrates the ancestral human population was never smaller than ~10,000 individuals (the bottleneck that would produce identical genomes if we all descended from two people would be detectable in modern genetic diversity — it is not). The "last common ancestors" of all human mitochondrial DNA (Mitochondrial Eve, ~150,000 BP) and Y-chromosomal DNA (Y-chromosomal Adam, ~300,000 BP) did not live at the same time.',
        'error': 'Human population never smaller than ~10,000 — a two-person bottleneck would leave a clear genetic signature absent from all modern humans',
        'category': 'biology',
        'sources': 'Population genetics; Mitochondrial Eve/Y-chromosomal Adam studies; hominid fossil record; comparative primate genomics',
    },
    {
        'id': 'light-before-sun',
        'icon': '💡',
        'claim': 'Genesis 1: God created light on Day 1 but the Sun, Moon, and stars on Day 4.',
        'what_science_says': 'The Sun formed approximately 4.6 billion years ago from the gravitational collapse of a molecular cloud. Its nuclear fusion produces photons (light). Light cannot exist without a source of electromagnetic radiation — there is no mechanism for light to precede the Sun. Starlight is photons from stars. The CMB (the oldest light) was released 380,000 years after the Big Bang — after the matter that would eventually form the Sun.',
        'error': 'Light (electromagnetic radiation) is produced by stars — it cannot precede the formation of stars',
        'category': 'physics',
        'sources': 'Stellar astrophysics; nuclear physics; cosmology of recombination epoch',
    },
    {
        'id': 'prayer-medicine',
        'icon': '🙏',
        'claim': 'Prayer has healing power. Miraculous cures occur through divine intervention (claimed across major religions).',
        'what_science_says': 'The largest randomised controlled trial of intercessory prayer (STEP, 2006, n=1,802) found no benefit and slight harm (more complications in the group that knew it was being prayed for). Cochrane systematic reviews of multiple prayer studies find no reliable clinical benefit. Apparent "miraculous" recoveries match base rates of spontaneous remission, late immune responses, and diagnostic revision.',
        'error': 'Not confirmed in any blinded, controlled clinical trial',
        'category': 'medicine',
        'sources': 'STEP study (Benson et al., 2006, American Heart Journal); Cochrane Database reviews of intercessory prayer',
    },
    {
        'id': 'bat-as-bird',
        'icon': '🦇',
        'claim': 'Leviticus 11:13–19 lists the bat among "birds" (winged creatures that are unclean).',
        'what_science_says': 'Bats are mammals (class Mammalia, order Chiroptera), not birds. They are warm-blooded, give birth to live young, produce milk, and have hair. Birds are avian dinosaurs (class Aves). This is a basic taxonomic error in a text claimed to be divinely authored by an omniscient creator who invented all animals.',
        'error': 'Bats have been correctly classified as mammals since John Ray (1693)',
        'category': 'biology',
        'sources': 'Systema Naturae (Linnaeus, 1758); modern mammalian taxonomy; comparative anatomy',
    },
    {
        'id': 'stars-falling',
        'icon': '⭐',
        'claim': 'Revelation 6:13: "The stars in the sky fell to earth, as figs drop from a fig tree when shaken by a strong wind." Matthew 24:29: "The stars will fall from the sky."',
        'what_science_says': 'The smallest star is ~80 times the mass of Jupiter and ~100,000 km in diameter. The nearest star is ~4.3 light-years away. A star "falling to Earth" is physically impossible — a star\'s gravity would either pull Earth into it or Earth would be vaporised by proximity long before contact. The Sun alone is 1.3 million times the volume of Earth. This reflects an ancient cosmology where stars were small lights fixed to a celestial dome.',
        'error': 'Stars are not small objects that can fall to Earth — the smallest are ~80× Jupiter\'s mass',
        'category': 'astronomy',
        'sources': 'Stellar astrophysics; nearest star: Alpha Centauri at 4.37 light-years; solar mass: 2×10³⁰ kg',
    },

    # ── Quran-specific entries ────────────────────────────────────────────────
    {
        'id': 'quran-sperm-backbone',
        'icon': '🧬',
        'scripture': 'Quran',
        'claim': 'Quran 86:5-7 — "Then let man consider from what he was created. He was created from a fluid, ejected, emerging from between the backbone and the ribs."',
        'what_science_says': 'Sperm is produced exclusively in the testes — two glands located outside the body in the scrotum, specifically because sperm production requires a temperature ~2°C cooler than core body temperature. Sperm passes through the vas deferens, seminal vesicles, and prostate before ejaculation. None of these structures are between the backbone and the ribs. The backbone (lumbar vertebrae) and ribs are the bony cage of the upper torso. This verse reflects a pre-scientific belief, common in ancient Arabia, that semen originated in the kidneys or loins. The kidneys are located near L1-L2 vertebrae — which is indeed between backbone and ribs — but the kidneys play no role in sperm production.',
        'error': 'Sperm is produced in the testes — not between backbone and ribs',
        'category': 'biology',
        'sources': 'Basic reproductive anatomy; testicular histology; sperm production requires 34-35°C (below core temperature of 37°C)',
    },
    {
        'id': 'quran-sun-muddy',
        'icon': '☀️',
        'scripture': 'Quran',
        'claim': 'Quran 18:86 — "Until, when he reached the setting of the sun, he found it setting in a spring of dark mud, and found a people thereabouts."',
        'what_science_says': 'The Sun is a star 1.39 million km in diameter located 150 million km from Earth. It does not "set" anywhere — the apparent sunset is caused by Earth\'s rotation. The Sun cannot set in a spring of mud or water, on Earth or anywhere else. This verse depicts the legendary traveller Dhul-Qarnayn observing the Sun physically descend into a muddy body of water — a phenomenology only possible if the Sun is a small object near the Earth\'s surface. No mainstream Islamic scholar successfully explains this verse as metaphor — the classical Quran commentaries (tafsir), including Al-Tabari (9th century), interpreted it literally: the Sun descending into the murky sea at the Western edge of the world.',
        'error': 'The Sun is 150 million km away and does not set in any earthly body of water',
        'category': 'astronomy',
        'sources': 'Al-Tabari, Tafsir (9th c.); Ibn Kathir, Tafsir; solar astronomy; Earth\'s rotation as cause of apparent sunset',
    },
    {
        'id': 'quran-mountains-pegs',
        'icon': '⛰️',
        'scripture': 'Quran',
        'claim': 'Quran 16:15 — "And He has cast into the earth firmly set mountains, lest it shift with you." Quran 78:6-7 — "Have We not made the earth a resting place? And the mountains as stakes/pegs?"',
        'what_science_says': 'Mountains do not prevent Earth from moving. Earth rotates at ~1,670 km/h at the equator, revolves around the Sun at ~107,000 km/h, and its tectonic plates move continuously (1–10 cm/year). Mountains are themselves produced by tectonic movement — they are the result of Earth\'s movement, not the prevention of it. The Himalayas are still rising because the Indian plate is still pushing into the Eurasian plate. Earthquakes — exactly the kind of "shifting" mountains supposedly prevent — occur most frequently in mountain-building zones. The "peg" model (mountains extending deep roots stabilising the crust like tent pegs) is geologically incorrect: mountains do have roots into the crust, but this provides isostatic balance, not seismic stability. Mountain ranges correlate with higher earthquake frequency, not lower.',
        'error': 'Mountains are created by tectonic movement and do not prevent earthquakes — they correlate with higher seismic activity',
        'category': 'geology',
        'sources': 'Plate tectonics; USGS seismic data; isostasy vs earthquake prevention; USGS: most earthquakes occur along tectonic plate boundaries, where mountains form',
    },
    {
        'id': 'quran-stars-missiles',
        'icon': '⭐',
        'scripture': 'Quran',
        'claim': 'Quran 67:5 — "And We have certainly beautified the nearest heaven with stars and have made [from] them what drives away the devils [shayatin], and We have prepared for them the punishment of the Blaze."',
        'what_science_says': 'Stars are nuclear fusion reactors. The smallest known star (EBLM J0555-57Ab) is ~85 Jupiter masses, ~85,000 km in diameter. The nearest star (Proxima Centauri) is ~4.24 light-years away — approximately 40 trillion km. They are not decorations placed in a "nearest heaven," nor are they missiles to repel supernatural beings. The verse also contains the cosmological framework of a "nearest heaven" — implying multiple stacked heavens with stars fixed to the innermost layer, a model borrowed from ancient Babylonian and Greek cosmology (the celestial spheres). The universe has no such structure.',
        'error': 'Stars are nuclear fusion reactors averaging millions of km in diameter — not decorations or weapons against demons',
        'category': 'astronomy',
        'sources': 'Stellar astrophysics; smallest known star: EBLM J0555-57Ab (2017); nearest star 40 trillion km away',
    },
    {
        'id': 'quran-seven-earths',
        'icon': '🌍',
        'scripture': 'Quran',
        'claim': 'Quran 65:12 — "It is Allah who has created seven heavens and of the earth, the like of them [seven earths]."',
        'what_science_says': 'There is one Earth. The solar system has eight planets. The Milky Way contains an estimated 100–400 billion stars with at least as many planets. The observable universe contains ~2 trillion galaxies. There is no physical, chemical, or astronomical basis for a cosmology of exactly "seven heavens" and "seven earths." This reflects the ancient Mesopotamian and Greek tradition of seven planetary spheres (Moon, Mercury, Venus, Sun, Mars, Jupiter, Saturn) that defined the cosmos in the pre-scientific world. The Quran inherited this cosmological framework from its cultural context, not from divine observation.',
        'error': 'There is one Earth and no "seven heavens" — the universe contains 2 trillion galaxies',
        'category': 'cosmology',
        'sources': 'Planetary science; Ptolemaic cosmology source of "seven heavens"; observable universe galaxy count: Conselice et al. (2016)',
    },
    {
        'id': 'quran-sky-roof',
        'icon': '🌤️',
        'scripture': 'Quran',
        'claim': 'Quran 21:32 — "And We have made the sky a preserved and protected roof." Quran 2:22 — "Who has made the earth a resting place for you and the sky a canopy."',
        'what_science_says': 'The sky is not a solid structure, roof, or canopy. "The sky" (the atmosphere) is a gradient of gases — nitrogen (78%), oxygen (21%), argon (0.9%), and traces — that thins gradually from ~100% density at sea level to near-vacuum at ~100 km altitude (the Kármán line). There is no boundary, dome, ceiling, or solid structure. Space probes launched since 1957 pass through it without hitting anything. Meteorites travel through it continuously. The ISS orbits at 400 km, above most of the atmosphere, inside "the sky." These verses reflect the ancient Near Eastern cosmological model of a solid sky-dome (raqia in Hebrew, also described in Genesis), a flat earth beneath it, and a physical ceiling holding back upper waters.',
        'error': 'The atmosphere is a gradual gas gradient with no roof — spacecraft pass through it in minutes',
        'category': 'physics',
        'sources': 'Atmospheric science; Kármán line; ISS orbital altitude 408 km; history of ancient Near Eastern cosmology',
    },
    {
        'id': 'quran-bones-before-flesh',
        'icon': '🦴',
        'scripture': 'Quran',
        'claim': 'Quran 23:14 — "Then We made the sperm-drop into a clinging clot, and We made the clot into a lump [of flesh], and We made the lump into bones, and We covered the bones with flesh; then We developed him into another creation."',
        'what_science_says': 'The verse describes a sequence where bones form first and are then covered with flesh. This is embryologically incorrect. Bone and muscle develop simultaneously from the same embryonic tissue layer — the mesoderm. The mesoderm differentiates in parallel into somites, which give rise to both skeletal muscle (myotomes) and the precursors of bone (sclerotomes) at the same developmental stage (weeks 3–8). Bones are not formed first and then wrapped in muscle — the two systems develop concurrently. This error is consistent with the ancient Greek understanding of embryology (Galen described a similar sequence of formation) that was current in 7th-century Arabia.',
        'error': 'Bone and muscle develop simultaneously from the same embryonic tissue (mesoderm) — bones do not form first',
        'category': 'biology',
        'sources': 'Human embryology (Moore & Persaud); somite development; mesodermal differentiation weeks 3-8 of gestation',
    },
    {
        'id': 'quran-flat-earth',
        'icon': '🗺️',
        'scripture': 'Quran',
        'claim': 'Quran 88:20 — "And at the earth — how it is spread out?" Quran 51:48 — "And the earth — We have spread it and excellent is the Spreader." Quran 15:19 — "And the earth — We have spread it and cast therein firmly set mountains."',
        'what_science_says': 'Earth is an oblate spheroid — a sphere slightly flattened at the poles and bulging at the equator — with a mean radius of 6,371 km. It is confirmed to be spherical by: circumnavigation (Magellan, 1519–1522), observations of Earth\'s circular shadow on the moon during lunar eclipses (noted by Aristotle, 350 BCE), the consistent horizontal curvature visible from altitude, satellite imagery since 1946, and GPS systems that require a spherical Earth model to function. Multiple Quranic verses describe the earth as "spread out" (Arabic: farasha, basata, madadna — all meaning to spread, flatten, or extend), consistent with an ancient flat-earth cosmology. Muslim scholars contest this, arguing the verbs can mean "spread out for habitation," but the same verbs in classical Arabic and the broader Quranic cosmological context (flat earth under a solid sky dome) support the flat-earth reading.',
        'error': 'Earth is a sphere — verified since ancient Greece; satellites require spherical Earth model to function',
        'category': 'geology',
        'sources': 'Geodesy; satellite imagery; GPS spherical Earth model; Aristotle\'s spherical Earth proofs (350 BCE); Eratosthenes\' measurement (240 BCE)',
    },
    {
        'id': 'quran-alexander-prophet',
        'icon': '⚔️',
        'scripture': 'Quran',
        'claim': 'Quran 18:83-98 — Dhul-Qarnayn ("The Two-Horned One"), traditionally identified by Islamic scholars as Alexander the Great, is described as a pious monotheist who "followed the way of the Lord" and enacted divine justice across the Earth.',
        'what_science_says': 'Alexander the Great (356–323 BCE) was a Greek polytheist. He worshipped Zeus, Athena, Dionysus, and Hercules; made sacrifices to multiple gods throughout his campaigns; claimed divine parentage from Zeus-Ammon after visiting the oracle at Siwa; adopted Persian and Egyptian deities into his personal worship; and died performing religious rites to the Babylonian god Marduk. He was by no description a monotheist or a follower of any Abrahamic tradition. He is also described in Quran 18:86 as observing the sun setting in a muddy spring (see above). The identification of Dhul-Qarnayn with Alexander is now contested by some Islamic scholars, but it was the standard exegesis of classical tafsir literature and remains the most common identification. If he is someone else, there is no historical record of any "two-horned" world-travelling monotheist king of this era.',
        'error': 'Alexander the Great was a Greek polytheist who worshipped multiple gods and claimed to be the son of Zeus',
        'category': 'history',
        'sources': 'Arrian, "Anabasis of Alexander"; Plutarch, "Life of Alexander"; Oracle of Siwa accounts; Babylonian astronomical diaries (Alexander\'s death rituals)',
    },
    {
        'id': 'quran-ants-talk',
        'icon': '🐜',
        'scripture': 'Quran',
        'claim': 'Quran 27:18-19 — "Until, when they came upon the valley of the ants, an ant said, \'O ants, enter your dwellings that you not be crushed by Solomon and his soldiers while they perceive not.\' So [Solomon] smiled, amused at her speech."',
        'what_science_says': 'Ants communicate exclusively through chemical signals (pheromones), tactile signals (antennal contact), and vibrational signals. They do not possess vocal cords, auditory organs for airborne speech, or neurological structures capable of generating or comprehending structured language. Ant "colonies" have no individual awareness of distant threats requiring verbal broadcast; they respond to chemical alarm signals released locally. The verse describes an ant issuing a verbal warning to an entire colony in advance of an approaching army — a cognitive and physiological capability ants categorically do not have. This is consistent with ancient anthropomorphic attributions of human-like speech to animals throughout Near Eastern literature.',
        'error': 'Ants have no vocal cords, no hearing organs for airborne speech, and no linguistic cognition',
        'category': 'biology',
        'sources': 'Myrmecology (ant biology); pheromone communication systems; Wilson & Hölldobler "The Ants" (1990, Pulitzer Prize)',
    },
    {
        'id': 'quran-human-from-clot',
        'icon': '🩸',
        'scripture': 'Quran',
        'claim': 'Quran 96:2 — "Created man from a clinging clot [alaq]." This is the first revealed verse — the foundational description of human origin in the Quran.',
        'what_science_says': 'Human reproduction begins with fertilisation of an egg (ovum, ~0.1 mm) by a sperm cell in the fallopian tube. The fertilised egg (zygote) divides into a blastocyst and implants in the uterine wall at ~6 days — this implantation could be described as "clinging." The term "alaq" in Arabic means a blood clot, leech, or something that clings. The broader embryological sequence in the Quran (sperm → clot → lump → bones → flesh) does not match human embryological development, which proceeds from zygote → blastocyst → gastrula → embryo with simultaneous tissue differentiation, not a sequential clot → lump → bone → flesh progression. The "clot" description reflects Aristotle\'s theory of embryology — widely accepted in the ancient world — in which menstrual blood was thought to be the material from which the embryo was formed, coagulated by male semen.',
        'error': 'Fertilised egg → blastocyst, not a blood clot; the sequence given in the Quran does not match embryological development',
        'category': 'biology',
        'sources': 'Human embryology (Sadler, "Langman\'s Medical Embryology"); Aristotle\'s embryology as historical source; comparative embryological timelines',
    },
    {
        'id': 'quran-two-seas',
        'icon': '🌊',
        'scripture': 'Quran',
        'claim': 'Quran 55:19-20 — "He released the two seas, meeting [side by side]; between them is a barrier [barzakh] which they do not transgress." Some Muslim apologists claim this predicts the scientific phenomenon of ocean haloclines.',
        'what_science_says': 'Ocean water masses do mix. Haloclines (density boundaries between water masses of different salinity) are real phenomena, but they are not permanent barriers — they are dynamic, temporary gradients that shift seasonally, are crossed by marine organisms constantly, and eventually fully mix over time through turbulence and diffusion. The Atlantic and Pacific oceans mix freely through the Drake Passage and Arctic Ocean. The Mediterranean and Atlantic mix continuously through the Strait of Gibraltar. There is no "barrier which they do not transgress" — mixing is ongoing. The verse was understood by early Islamic scholars as referring to fresh and salt water not mixing (e.g. river estuaries), a common ancient Near Eastern observation, not a sophisticated prediction of modern oceanography. Estuarine mixing zones do exist, but the claim that salt and fresh water "do not mix" is false — they mix completely downstream in every river delta.',
        'error': 'Oceans and water bodies mix continuously — haloclines are temporary gradients, not permanent barriers',
        'category': 'geology',
        'sources': 'Physical oceanography; Drake Passage mixing; Gibraltar exchange current; estuarine mixing dynamics',
    },
    {
        'id': 'quran-quran-embryology-sequence',
        'icon': '🔬',
        'scripture': 'Quran',
        'claim': 'Muslim apologists (notably Dr. Keith Moore, formerly of the University of Toronto) claim that Quranic embryology (Quran 22:5, 23:12-14) contains scientific knowledge impossible for a 7th-century author to possess.',
        'what_science_says': 'The embryological descriptions in the Quran closely match the theories of Galen of Pergamon (129–216 CE), the most authoritative Greek physician in the medieval Islamic world — whose works were translated into Arabic in the 8th–9th centuries. Galen described embryological development as: seed → blood → flesh → bones in sequence, virtually identical to the Quranic account. This is not a surprising parallel if the Quran reflects the common knowledge of its time — it is a surprising claim if it represents miraculous prediction. Keith Moore\'s 1983 paper endorsing Quranic embryology was a paid consultation funded by Saudi Arabia and has been widely criticised; the descriptions he praised were reinterpretations of ambiguous Arabic terms to match modern findings, not straightforward accurate descriptions. His co-author later distanced himself from the claims.',
        'error': 'Quranic embryology matches Galen\'s 2nd-century Greek medical theories, not modern science',
        'category': 'biology',
        'sources': 'Galen, "On Semen" and "On the Formation of the Foetus" (2nd c. CE); Duane Gish critique of Moore (1993); T.W. Sadler response to i\'jaz claims',
    },
]

DESIGNED_VS_ACTUAL = [
    {
        'aspect': 'Age',
        'designed': 'Created for humanity: should have been ready for human habitation immediately or shortly after creation.',
        'actual': 'Universe: 13.8 billion years old. Earth: 4.54 billion years old. Homo sapiens: 300,000 years old. Humans have existed for 0.002% of Earth\'s history and 0.000002% of cosmic time.',
        'verdict': 'Humans arrived in the last 0.000002% of cosmic history.',
    },
    {
        'aspect': 'Space for Life',
        'designed': 'If designed for life, life should be common or the space dedicated to life should dominate.',
        'actual': '99.9999% of the universe\'s volume is lethal vacuum, extreme radiation, gravitational tidal forces, or temperatures incompatible with biochemistry. Life is confirmed on exactly 1 of ~10²⁴ known stars\' planets.',
        'verdict': 'Life exists in a fraction of space so small it requires scientific notation to express.',
    },
    {
        'aspect': 'Species Survival',
        'designed': 'A creator who made species for a purpose should want them to persist.',
        'actual': '99.9% of all species that have ever existed are extinct. Five mass extinctions have killed 70–96% of all species at various points. Extinction is the norm, survival the exception.',
        'verdict': '99.9% failure rate for species.',
    },
    {
        'aspect': 'Suffering in Nature',
        'designed': 'A loving designer would minimise gratuitous suffering — especially for beings with no moral lessons to learn.',
        'actual': 'Evolution requires predation, parasitism, starvation, and disease as its engine. Parasitic wasps lay eggs inside living caterpillars; Cordyceps fungi consume ants from the inside. These adaptations are optimised by natural selection for efficiency, not minimised for compassion.',
        'verdict': 'Suffering is the mechanism of life, not a side effect.',
    },
    {
        'aspect': 'Human Body',
        'designed': 'A perfect designer would produce an optimally functional body.',
        'actual': 'Backwards retina, recurrent laryngeal nerve looping metres in giraffes, birth canal too narrow for the skull, shared airway/food passage, sinuses that drain upward against gravity, wisdom teeth, appendix that can kill, knees unsuited for bipedalism. (See: Bad Design topic for full catalogue.)',
        'verdict': 'Every body flaw is predicted by evolutionary history and inexplicable by design.',
    },
    {
        'aspect': 'Brain Design',
        'designed': 'A designed mind should be accurate, reliable, and resistant to delusion.',
        'actual': 'The human brain systematically hallucinates, confabulates, is prone to cognitive bias, generates false memories, cannot distinguish vivid dreams from reality, is hijacked by parasites (Toxoplasma gondii), produces schizophrenia, depression, and Alzheimer\'s disease — and, as CSR shows, reliably generates belief in false supernatural agents as a by-product of evolved heuristics.',
        'verdict': 'A mind designed to find truth would not be this reliably wrong.',
    },
    {
        'aspect': 'Disease',
        'designed': 'A designer of life would not include pathogens that kill children.',
        'actual': 'Before modern medicine, ~50% of children died before adulthood. Diseases like smallpox, tuberculosis, malaria, and cholera have killed billions. Cancer affects 40% of humans. The immune system regularly attacks itself. Viruses evolve specifically to subvert our defences.',
        'verdict': 'Disease kills children at the highest rates — a loving designer\'s worst possible outcome.',
    },
    {
        'aspect': 'Moral Distribution',
        'designed': 'A just, aware God would distribute natural suffering in proportion to moral merit.',
        'actual': 'Earthquakes, floods, cancer, and genetic disease are distributed in accordance with geology, meteorology, and biochemistry — with zero correlation to moral character, age, innocence, or religious belief. Children in countries with no fault lines get cancer. Devout people die in earthquakes.',
        'verdict': 'The distribution of suffering matches indifferent physics, not divine judgment.',
    },
    {
        'aspect': 'Communication',
        'designed': 'A God who wants to be known and wants belief would communicate clearly and universally.',
        'actual': 'Of ~108 billion humans ever born, most lived in times and places with no access to any specific religion\'s revelatory claims. ~15% of current humanity is non-religious. No message from any god has ever been delivered in a form verifiable by independent observers. All claimed revelations are culturally and geographically localised.',
        'verdict': 'God\'s communication strategy has reached a minority of humanity, ambiguously.',
    },
]

PHILOSOPHY_TREE = [
    {
        'id': 'cosmological',
        'name': 'Cosmological Argument',
        'icon': '💥',
        'color': '#a855f7',
        'premise': 'Everything that exists has a cause. The universe exists. Therefore the universe has a cause (God).',
        'best_version': 'The Kalam Cosmological Argument (William Lane Craig): "Everything that begins to exist has a cause. The universe began to exist. Therefore, the universe has a cause." The cause must be timeless, spaceless, immensely powerful — i.e., God.',
        'rebuttals': [
            {'title': 'Special Pleading', 'body': 'If everything that exists needs a cause, God also needs a cause. Craig exempts God by saying He is eternal and uncaused — but the same property (eternal, uncaused existence) can be attributed to the quantum vacuum, the multiverse, or the laws of physics, without requiring God.'},
            {'title': 'The Quantum Vacuum Refutation', 'body': 'Quantum mechanics shows that events can occur without prior classical causes — virtual particles appear and disappear without causal antecedents in the classical sense. The Heisenberg uncertainty principle (ΔE·Δt ≥ ℏ/2) makes a truly causeless quantum vacuum energetically necessary. "Begins to exist" in the Kalam may not apply to the universe in the quantum cosmological sense.'},
            {'title': 'The Hartle-Hawking Refutation', 'body': 'In the no-boundary proposal, time itself emerges from quantum geometry at the Big Bang. "Before the Big Bang" is meaningless because time did not exist. A universe with no temporal beginning cannot "begin to exist" in the sense the Kalam requires. Hawking: asking what happened before the Big Bang is like asking what is south of the South Pole.'},
            {'title': 'Even If Valid, Proves Very Little', 'body': 'Even if the argument establishes a "first cause," this cause need not be conscious, personal, omnipotent, omniscient, or interested in human affairs. A brute physical law or quantum fluctuation satisfies "cause" without having divine properties.'},
        ],
    },
    {
        'id': 'teleological',
        'name': 'Teleological Argument (Design)',
        'icon': '⚙️',
        'color': '#00d4ff',
        'premise': 'The universe and life show signs of design and purpose. Design requires a designer. Therefore God exists.',
        'best_version': 'William Paley\'s Watchmaker (1802): A watch found on a heath implies a watchmaker. The eye implies a designer. The fine-tuning argument: physical constants are so precisely set for life that only intentional design can explain them.',
        'rebuttals': [
            {'title': 'Natural Selection Eliminates the Design Inference for Biology', 'body': 'Darwin\'s insight: complex, functional structures can be produced by blind, undirected cumulative selection operating on random variation. There is no need for a designer. Every specific biological "design" argument (the eye, the bacterial flagellum, the blood-clotting cascade) has been answered by evolutionary biology with a precise mechanism.'},
            {'title': 'Fine-Tuning: Anthropic Selection Refutation', 'body': 'We can only observe a universe compatible with observers. In a multiverse of varying constants, observers by definition find themselves in a life-permitting subset — without design. This is the same reason you\'re on a planet and not floating in empty space, without needing Earth to have been specially designed.'},
            {'title': 'Bad Design Refutes Good Design', 'body': 'The same universe cited as "designed for life" contains 10²⁴ stars, 99.9999% of which support no life; 99.9% species extinction; a human body full of evolutionary compromises. A good designer would not produce this. Evolution would, and does.'},
            {'title': 'Stenger\'s MonkeyGod Simulations', 'body': 'Victor Stenger\'s computer simulations varied the gravitational and electromagnetic constants randomly across many orders of magnitude and found that stars (prerequisite for heavy elements and life) formed in ~50% of all trials. The fine-tuning is not as narrow as claimed.'},
        ],
    },
    {
        'id': 'ontological',
        'name': 'Ontological Argument',
        'icon': '∞',
        'color': '#f97316',
        'premise': 'God is defined as the greatest conceivable being. A being that exists is greater than one that doesn\'t. Therefore God must exist.',
        'best_version': 'Anselm (1078): God is "that than which nothing greater can be conceived." If God existed only in the mind, a greater God (one that also exists in reality) could be conceived. Contradiction: therefore God must exist in reality.',
        'rebuttals': [
            {'title': 'Gaunilo\'s Island Refutation (1078)', 'body': 'Anselm\'s contemporary Gaunilo immediately replied with a parody: "The greatest conceivable island must exist, by the same reasoning." If the argument worked for God, it would work for any "greatest conceivable X" — which is absurd. The argument proves too much.'},
            {'title': 'Kant: Existence Is Not a Predicate', 'body': 'Immanuel Kant\'s devastating 1781 critique: "existence" is not a property or predicate that adds to a concept. Saying "God is omnipotent, omniscient, and exists" does not add a new property — existence is not a feature a concept can have. You cannot define something into existence.'},
            {'title': 'Modal Logic Version Also Fails', 'body': 'The modal ontological argument (Plantinga) uses possible-worlds logic but requires assuming its conclusion (that God\'s existence is possible in the relevant sense) to get started. Equally, if God\'s non-existence is possible in any world, the argument fails. The starting premise smuggles in the conclusion.'},
        ],
    },
    {
        'id': 'moral',
        'name': 'Moral Argument',
        'icon': '⚖️',
        'color': '#22c55e',
        'premise': 'Objective moral facts exist. Objective moral facts require a foundation. God is that foundation. Therefore God exists.',
        'best_version': 'C.S. Lewis: "If there is no God, there is no objective morality — only subjective preference. But we all act as if some things are really wrong (torturing children). This objective moral reality points to God."',
        'rebuttals': [
            {'title': 'Euthyphro Dilemma (Plato, 380 BCE)', 'body': 'Is something good because God commands it, or does God command it because it\'s good? If the former: morality is arbitrary (God could command torture and it would be "good"). If the latter: goodness is independent of God and doesn\'t require Him. Either way, God is not the source of morality.'},
            {'title': 'Evolutionary Ethics', 'body': 'Morality has evolutionary and neurological foundations: empathy, reciprocity, fairness, and cooperation are traits that improved survival and reproductive success in social primates. Frans de Waal documents these in chimpanzees and bonobos. These are naturalistic foundations for ethics requiring no God.'},
            {'title': 'Divine Command History Is Atrocious', 'body': 'The God who is supposed to be the foundation of objective morality commanded slavery (Leviticus 25), genocide (Deuteronomy 7), the murder of non-virgin brides (Deuteronomy 22), and the killing of people who work on the Sabbath (Exodus 35:2). If these are the outputs of an objective moral foundation, the foundation is worse than human moral reasoning.'},
        ],
    },
    {
        'id': 'transcendental',
        'name': 'Transcendental Argument for God (TAG)',
        'icon': '🧮',
        'color': '#22c55e',
        'premise': 'Logic, mathematics, and the laws of nature are abstract, universal, necessary truths. Their existence requires a rational mind that grounds them. That mind is God.',
        'best_version': 'Cornelius Van Til / Greg Bahnsen: Without God, logic and reason cannot be justified. The atheist "borrows capital" from the Christian worldview every time they use logic to argue against God. The very existence of rational thought, mathematical truths, and natural laws presupposes a rational Creator who established them.',
        'rebuttals': [
            {'title': 'Mathematical Platonism Needs No Creator', 'body': 'Mathematical truths are necessary — true in all possible worlds — but this does not mean they need a mind to make them true. The number 2 was prime before any mind existed to know it. Mathematical objects, under Platonism, are abstract entities that exist independently of any mind, including God. Appealing to God to ground mathematical truth is circular: a God who "knows" mathematics must use logic to think, so logic is prior to God rather than dependent on Him.'},
            {'title': 'The Argument Applies to Every Possible God Equally', 'body': 'If logic requires a "rational mind" to ground it, any rational mind would do — not specifically the Christian God. The argument equally "proves" Zeus, Brahma, or a deistic watchmaker. It selects no specific deity because it does not explain what properties the logical-grounding mind must have beyond rationality.'},
            {'title': 'Logic May Be a Feature of Any Consistent Universe', 'body': 'Logic describes the rules of consistent description — contradiction is logically impossible in any possible world because self-contradiction is incoherent, not because a God forbids it. The laws of logic are not brute facts requiring explanation — they are constraints on coherent description. A self-contradictory universe is not a possible object of description at all, regardless of whether any God exists.'},
            {'title': 'Self-Refutation: Does God Follow Logic?', 'body': 'If God grounds logic, then logic depends on God\'s will — meaning God could have made contradictions true, and logic would be contingent. If, alternatively, God follows logic because He is rational by nature, then logic is prior to and independent of God. Either way, TAG fails: either logic is arbitrary (God-dependent and contingent) or it is independent of God (not requiring Him as its ground).'},
        ],
    },
    {
        'id': 'miracles',
        'name': 'Argument from Miracles',
        'icon': '✨',
        'color': '#fbbf24',
        'premise': 'Historically documented miracles — healings, resurrections, prophetic fulfillments — can only be explained by divine intervention. Therefore God exists.',
        'best_version': 'Richard Swinburne\'s Bayesian defense: Given the prior probability of God\'s existence, the testimony of multiple independent witnesses to miraculous events raises the posterior probability of both the miracles and God significantly. The resurrection of Jesus, documented within decades by multiple independent sources, is best explained as a real divine event.',
        'rebuttals': [
            {'title': 'Hume\'s Maxim: Miracle Reports vs Actual Miracles', 'body': 'David Hume (1748): the probability that a miracle occurred must always be weighed against the probability that witnesses were mistaken, deceived, or deceiving. Human testimony is frequently wrong — people hallucinate, confabulate, lie, exaggerate, and spread stories that improve with retelling. Since miracles by definition violate well-established natural regularities, the probability of any natural explanation (error, fraud, illusion) is always higher than the probability that the laws of nature were suspended.'},
            {'title': 'All Religions Have Incompatible Miracle Claims', 'body': 'If miracle testimony validates Christianity, it equally validates every other religion with documented miracles. Hinduism has extensive miracle traditions. Islam has Quran-documented miracles. Buddhism has countless. Ancient Rome documented divine miracles before Christianity existed. If the standard for accepting a miracle is testimonial consistency and cultural impact, pagan Roman miracles should be taken just as seriously. They cannot all be true. The mutual inconsistency of religious miracle claims means they systematically cancel each other out.'},
            {'title': 'The Resurrection: Evidence Is Far Too Weak', 'body': 'The earliest testimony for the resurrection (Paul\'s letters, ~20 years after the event) claims appearance to 500 people, but Paul never interviewed them and no group testimony has been preserved. The Gospels were written 35-65 years after the events by non-eyewitness authors, contain clear contradictions (number of women at the tomb, appearances reported), and were written in a cultural environment where resurrection stories were neither unprecedented nor implausible. Each naturalistic explanation — grief-induced hallucination, moved body, legendary accretion — is independently more probable than physical resurrection, which would require suspension of thermodynamics, cellular biology, and decay chemistry.'},
            {'title': 'Modern Miracle Claims Are Never Verified Under Scrutiny', 'body': 'No claimed miraculous healing involves the regeneration of a severed limb, the reversal of a documented chromosomal abnormality, or any event requiring genuinely supernatural intervention as opposed to spontaneous remission. Every examined "miracle healing" falls within the natural distribution of outcomes. No amputee has ever been cured by prayer. The Catholic Church\'s rigorous miracle-verification process for canonization has never produced a verified case that requires abandoning natural explanation.'},
        ],
    },
    {
        'id': 'consensus',
        'name': 'Argument from Universal Religious Belief',
        'icon': '🌍',
        'color': '#94a3b8',
        'premise': 'Religious belief is universal across all human cultures and throughout all of recorded history. This universality suggests religion is tracking something real — an actual divine reality.',
        'best_version': 'C.S. Lewis\'s "Tao" argument: Every culture throughout history has believed in some form of moral law and some form of divine reality. The universality of these intuitions suggests they are not invented but discovered — tracking an actual moral order and an actual divine being that all cultures have independently encountered.',
        'rebuttals': [
            {'title': 'Universal Belief Does Not Entail Truth', 'body': 'Every human culture throughout history also believed in a geocentric universe. Every culture believed in spontaneous generation. Every culture believed thunder was supernatural. Universal and persistent human beliefs are frequently wrong. The question is not how many people believe something, but whether there is independent evidence for it. There is none for any deity.'},
            {'title': 'Cognitive Science Explains Universality Without Truth', 'body': 'The cognitive science of religion (Boyer, Barrett, Norenzayan) explains religious belief universality as a predictable consequence of evolved cognitive architecture: agency detection, theory of mind, minimally counterintuitive concepts, and afterlife belief all arise from general cognitive systems, not from contact with the divine. The universality of religion is evidence about human psychology — not about external reality.'},
            {'title': 'The Content of Universal Religion Is Radically Contradictory', 'body': 'The "universality" of religion abstracts over the fact that the specific content of religious beliefs is radically diverse and mutually incompatible. Polytheism, monotheism, pantheism, animism, and non-theistic religions (Buddhism, Jainism, Taoism) cannot all be tracking the same divine reality. The universal feature is belief in something supernatural, not agreement on what that something is — and mutual incompatibility is the opposite of convergent evidence.'},
            {'title': 'The Secular World Is Disproving the Universality Claim', 'body': 'Approximately 1.2 billion people worldwide now identify as non-religious, with the non-religious growing faster than any specific religion. Countries like the Czech Republic, Estonia, Japan, South Korea, and the Netherlands have majority non-religious populations while maintaining functional, ethical, cooperative societies. The demographic transition away from religion tracks education and economic security — exactly what we expect if religion responds to uncertainty and existential need, not divine reality.'},
        ],
    },
    {
        'id': 'experiential',
        'name': 'Argument from Religious Experience',
        'icon': '✨',
        'color': '#fbbf24',
        'premise': 'Many people across all cultures report direct personal experiences of God or the divine. These experiences are real and significant. Therefore God exists.',
        'best_version': 'William Alston: perceiving God is analogous to perceiving the physical world — both are direct, non-inferential experiences. We trust physical perception; we should trust religious perception.',
        'rebuttals': [
            {'title': 'Pharmacological Reproducibility', 'body': 'Every component of religious experience is reproducible by chemical means: psilocybin produces "the most meaningful experience of my life" (61% of subjects, Johns Hopkins); ketamine reproduces NDEs; DMT produces "entity encounters"; temporal lobe stimulation produces "sensed presence." If a molecule reproduces the experience, the molecule (not the divine) is the mechanism.'},
            {'title': 'Cultural Specificity', 'body': 'Christians see Jesus; Hindus see Krishna; Buddhists perceive emptiness; indigenous Americans encounter their own spirit beings. If experiences were contacts with an objective divine being, the being\'s identity should not vary with the experiencer\'s cultural background. It varies perfectly.'},
            {'title': 'Conflicting Claims Cancel Out', 'body': 'Millions of people have religious experiences that are mutually contradictory — experiences confirming the Trinity, experiences confirming strict monotheism (incompatible with the Trinity), experiences confirming polytheism. They cannot all be accurate perceptions of the same objective reality.'},
        ],
    },
]
