DEBUNKED = [
    {
        'id': 'theory-myth',
        'claim': '"Evolution is just a theory — it hasn\'t been proven."',
        'category': 'evolution',
        'icon': '🧬',
        'color': 'var(--evolution)',
        'verdict': 'MYTH',
        'short_rebuttal': 'In science, "theory" means the highest level of tested explanation — not a guess. Gravity is "just a theory." Germ theory is "just a theory."',
        'full_rebuttal': 'In everyday language "theory" means a guess. In science it means a rigorously tested, evidence-based explanation of natural phenomena. Gravity is "just a theory." Germ theory is "just a theory." Plate tectonics is "just a theory." Evolution is confirmed by the fossil record, molecular genetics, comparative anatomy, direct observation of speciation, and genomic sequencing across millions of species. To call it unproven is to fundamentally misunderstand what scientific proof means.',
        'evidence': [
            'The fossil record shows an unambiguous progression from simpler to more complex life over 3.8 billion years.',
            'DNA sequencing confirms common ancestry — humans share 98.7% of coding DNA with chimpanzees.',
            'We have directly observed speciation in real time — bacteria, insects, fish, and plants evolving into distinct species under controlled conditions.',
            'Endogenous retroviruses — ancient viral DNA fragments — found at identical genome locations in humans and chimpanzees prove a shared infected ancestor.',
        ],
        'source_claim': 'Creationist literature and religious education curricula',
        'quote': {'text': 'Nothing in biology makes sense except in the light of evolution.', 'author': 'Theodosius Dobzhansky, geneticist · American Biology Teacher, 1973'},
    },
    {
        'id': 'einstein-god',
        'claim': '"Einstein believed in God — science and religion are compatible."',
        'category': 'reason',
        'icon': '⚡',
        'color': 'var(--reason)',
        'verdict': 'MISLEADING',
        'short_rebuttal': 'Einstein explicitly rejected a personal God and called the Bible "primitive legends." His use of "God" was a poetic metaphor for the rational structure of nature.',
        'full_rebuttal': 'Einstein used the word "God" poetically to mean the orderly, mathematical structure of the universe — not a personal deity who answers prayers or created humanity. In his 1954 letter to Eric Gutkind (sold at auction for $2.9 million), he wrote: "The word God is for me nothing more than the expression and product of human weaknesses, and the Bible a collection of honourable but still primitive legends." He called himself "agnostic" and explicitly distanced himself from any theism. The viral quote "The more I study science, the more I believe in God" was never said by him — it is a fabrication with no verified source.',
        'evidence': [
            '"The word God is for me nothing more than the expression and product of human weaknesses." — Einstein, letter to Eric Gutkind, January 3, 1954.',
            '"I do not believe in a personal God and I have never denied this but have expressed it clearly." — Einstein, 1954.',
            'Einstein described his religion as "unbounded admiration for the structure of the world that science has been able to reveal" — explicitly not theism.',
            'The quote "The more I study science, the more I believe in God" has never been found in any verified Einstein letter, book, or interview.',
        ],
        'source_claim': 'Religious apologetics and widespread misquote campaigns',
        'quote': {'text': 'I cannot imagine a God who rewards and punishes the objects of his creation, whose purposes are modeled after our own — a God who is but a reflection of human frailty.', 'author': 'Albert Einstein'},
    },
    {
        'id': 'fine-tuning',
        'claim': '"The universe\'s physical constants are so fine-tuned for life they must have been designed by God."',
        'category': 'cosmology',
        'icon': '💥',
        'color': 'var(--cosmology)',
        'verdict': 'FLAWED',
        'short_rebuttal': 'Fine-tuning is real, but design is not the only or best explanation. Anthropic selection, the multiverse, and unknown physics all offer non-supernatural alternatives.',
        'full_rebuttal': 'The fine-tuning argument has two premises: (1) physical constants could have been different; (2) design is the most probable explanation for their values. Both are contested. First, we don\'t know whether the constants could vary — they may be fixed by a deeper theory not yet discovered. Second, even granting design as one explanation, we can only observe a universe compatible with observers — the Anthropic Principle. In a multiverse of varying constants, observers by definition find themselves in life-permitting ones. Invoking God merely relocates the problem: where did a fine-tuned God capable of designing physics come from?',
        'evidence': [
            'The Anthropic Principle: any universe we observe must support observers by definition — we cannot sample empty universes.',
            'String theory landscape: some formulations predict ~10⁵⁰⁰ possible vacuum states with different constants, making ours statistically expected in a multiverse.',
            'Victor Stenger\'s MonkeyGod simulations showed that many randomly chosen constant combinations still permit long-lived, complex universes.',
            'We have no evidence that the constants are free parameters — a complete theory of quantum gravity may fix them uniquely with no room for "tuning."',
        ],
        'source_claim': 'Intelligent Design movement; cosmological argument for God (Kalam)',
        'quote': {'text': 'The fine-tuning argument is a profound failure of imagination — we cannot count possibilities we have no access to.', 'author': 'Sean Carroll, theoretical physicist, Caltech'},
    },
    {
        'id': 'second-law',
        'claim': '"The Second Law of Thermodynamics disproves evolution — disorder can\'t spontaneously produce order."',
        'category': 'evolution',
        'icon': '🔥',
        'color': 'var(--evolution)',
        'verdict': 'MYTH',
        'short_rebuttal': 'The Second Law applies to closed systems. Earth is an open system receiving ~174 petawatts of energy continuously from the Sun.',
        'full_rebuttal': 'The Second Law of Thermodynamics states that total entropy increases in an isolated (closed) system. Earth is not a closed system — it receives approximately 1.74 × 10¹⁷ watts of energy from the Sun and radiates heat into space. This energy input permits local decreases in entropy (increases in order) without violating thermodynamics. Life, snowflakes, crystals, and hurricanes all represent local order in an open system. The total entropy of the Earth-Sun system increases even as life evolves — perfectly consistent with the Second Law.',
        'evidence': [
            'Earth receives ~174 petawatts of solar energy continuously, making it an open system where local decreases in entropy are thermodynamically permitted.',
            'Crystals spontaneously form ordered lattices from disordered solutions — no law of thermodynamics is violated.',
            'Every refrigerator creates local cold (decreased entropy inside) by expelling heat to the environment — open-system entropy reduction happening in every kitchen.',
            'Total entropy of Earth + Sun + radiative losses increases even as biological complexity evolves — the Second Law is satisfied.',
        ],
        'source_claim': 'Creationist and Intelligent Design literature; repeated in debates since Henry Morris (1974)',
        'quote': {'text': 'The creationist misuse of the Second Law of Thermodynamics is the most elementary thermodynamics error I have encountered in public discourse.', 'author': 'Daniel Styer, physicist, Oberlin College'},
    },
    {
        'id': 'transitional-fossils',
        'claim': '"There are no transitional fossils — if evolution were true, the record would be full of them."',
        'category': 'evolution',
        'icon': '🦴',
        'color': 'var(--evolution)',
        'verdict': 'MYTH',
        'short_rebuttal': 'We have thousands of transitional fossils, including fish-to-tetrapod, dinosaur-to-bird, land-mammal-to-whale, and the complete human fossil record.',
        'full_rebuttal': 'This claim was outdated when Darwin was alive — he himself listed known transitional forms in "On the Origin of Species" (1859). We now have thousands of transitional fossils across every major evolutionary transition. Tiktaalik (2004): a 375-million-year-old fish with wrist-like fins, exactly at the fish-to-tetrapod transition predicted in advance by evolutionary theory. The dinosaur-to-bird transition is documented by Archaeopteryx and 30+ species of feathered dinosaurs. Whale evolution is documented by a complete series from Pakicetus (land mammal, 50 Ma) to modern cetaceans. The human fossil record shows Ardipithecus, Australopithecus, Homo habilis, Homo erectus, and Homo heidelbergensis in exact evolutionary sequence.',
        'evidence': [
            'Tiktaalik roseae (2004): a 375 Ma fish with fins containing wrist and finger bones — exactly the fish-to-tetrapod intermediate predicted before its discovery.',
            'Archaeopteryx and 30+ feathered dinosaur species bridge the dinosaur-bird gap with complete gradational series.',
            'Whale evolution: Pakicetus (land mammal, 50 Ma) → Ambulocetus (semi-aquatic) → Rodhocetus (fully aquatic, 46 Ma) → modern whales.',
            'Human fossil series: Sahelanthropus (7 Ma), Ardipithecus (4.4 Ma), Australopithecus (3.9 Ma), Homo habilis (2.8 Ma), Homo erectus (1.9 Ma), Homo sapiens (0.3 Ma).',
        ],
        'source_claim': 'Creationist and Intelligent Design literature since the 19th century',
        'quote': {'text': 'We have fossils. We win.', 'author': 'Richard Dawkins · The God Delusion, 2006'},
    },
    {
        'id': 'big-bang-nothing',
        'claim': '"The Big Bang says everything came from nothing — that requires a creator."',
        'category': 'cosmology',
        'icon': '🌌',
        'color': 'var(--cosmology)',
        'verdict': 'MISLEADING',
        'short_rebuttal': 'The Big Bang describes the expansion of a hot, dense state — it does not claim the universe arose from philosophical "nothing." That remains an open scientific question.',
        'full_rebuttal': 'The Big Bang theory describes the universe\'s evolution from an extremely hot, dense early state ~13.8 billion years ago. It does not say the universe appeared from nothing in the philosophical sense. The physics of the very first instant (the Planck epoch, <10⁻⁴³ seconds) requires quantum gravity, which we don\'t yet have. Hawking and Hartle\'s No-Boundary Proposal (1983) describes a universe with no temporal beginning — time itself emerges from quantum geometry. Lawrence Krauss\'s "A Universe from Nothing" shows how quantum field theory allows matter to arise from vacuum energy. Invoking God simply relocates the problem: an eternal, omnipotent God capable of creating physics requires just as much explanation as an eternal quantum vacuum.',
        'evidence': [
            'The Big Bang model describes expansion from a hot, dense state — the origin of that state is an open scientific question, not answered by invoking God.',
            'Hawking-Hartle No-Boundary Proposal (1983): in imaginary time, the universe has no beginning — asking what happened before the Big Bang is like asking what is south of the South Pole.',
            'Quantum field theory demonstrates spontaneous particle pair production from vacuum energy — "nothing" in physics is not the same as philosophical nothing.',
            'The CMB matches Big Bang predictions to 1 part in 100,000 — the expansion history is confirmed; the origin remains a scientific frontier.',
        ],
        'source_claim': 'Cosmological argument for God (Kalam); apologist William Lane Craig',
        'quote': {'text': 'Because there is a law like gravity, the universe can and will create itself from nothing. It is not necessary to invoke God.', 'author': 'Stephen Hawking · The Grand Design, 2010'},
    },
    {
        'id': 'morality-god',
        'claim': '"Without God, there is no objective morality. Atheism leads to nihilism and amorality."',
        'category': 'reason',
        'icon': '⚖️',
        'color': 'var(--reason)',
        'verdict': 'MYTH',
        'short_rebuttal': 'Morality has deep evolutionary, neurological, and philosophical foundations that require no supernatural justification. The Divine Command Theory is philosophically fatal.',
        'full_rebuttal': 'The claim collapses under scrutiny. First, the Euthyphro Dilemma (Plato, 380 BCE): Is something good because God commands it, or does God command it because it\'s good? If the former, morality is arbitrary — God could command child murder and it would be "moral." If the latter, goodness is independent of God. Second, evolutionary psychology shows empathy, fairness, and cooperation have deep roots shared with non-human primates — Frans de Waal documented these in chimpanzees and bonobos. Third, secular moral philosophy (utilitarianism, contractarianism, virtue ethics) provides rigorous frameworks for ethics without religion. Historically, divine command has justified slavery, genocide, and inquisitions.',
        'evidence': [
            'Euthyphro Dilemma (Plato, 380 BCE): divine command theory makes morality either arbitrary (God could command evil) or God-independent — both fatal to the argument.',
            'Frans de Waal\'s primate research documents empathy, fairness, consolation, and reciprocity in chimpanzees and bonobos with no exposure to religious teaching.',
            'Secular moral philosophy provides robust, internally consistent frameworks: utilitarianism, Kantian deontology, Rawlsian contractarianism.',
            'Divine command has historically justified: African slave trade (Leviticus 25:44–46), the Crusades, the Inquisition, genocide (Deuteronomy 7:1–2), and female subjugation.',
        ],
        'source_claim': 'Moral argument for God; C.S. Lewis\'s "Mere Christianity"; religious apologetics generally',
        'quote': {'text': 'If you think morality requires God, you are simply wrong about where morality comes from — and the science of it is now clear.', 'author': 'Sam Harris, neuroscientist · The Moral Landscape, 2010'},
    },
    {
        'id': 'consciousness-gap',
        'claim': '"Science can\'t explain consciousness, therefore the soul and God must exist."',
        'category': 'reason',
        'icon': '🧠',
        'color': 'var(--reason)',
        'verdict': 'FLAWED',
        'short_rebuttal': '"We don\'t fully understand X, therefore God" is the God of the Gaps fallacy. Neuroscience has mapped consciousness to specific brain processes with extraordinary precision.',
        'full_rebuttal': 'The "hard problem of consciousness" is a genuine open question in philosophy of mind — but "we don\'t fully understand it" is not evidence for the supernatural. This is the God of the Gaps fallacy: filling scientific unknowns with deity. Historically, lightning, disease, mental illness, and the origin of life were all filled with God — each subsequently explained by natural processes. We know precisely that: damage to Broca\'s area causes speech loss; damage to the fusiform face area causes face blindness; specific anesthetics abolish consciousness by disrupting specific neural oscillations. The soul predicts none of these correlations. Neuroscience explains all of them.',
        'evidence': [
            'Specific brain lesions cause specific, predictable losses of experience: Broca\'s area → speech; HM\'s hippocampus → memory formation; fusiform face area → face recognition.',
            'Anesthesia reversibly abolishes consciousness by disrupting thalamocortical gamma oscillations — no immaterial soul is required or predicted.',
            'Split-brain patients (severed corpus callosum) behave as if they have two separate streams of consciousness — incompatible with a unified immaterial soul.',
            'Integrated Information Theory, Global Workspace Theory, and Predictive Processing provide serious neuroscientific frameworks for consciousness without invoking the supernatural.',
        ],
        'source_claim': 'Religious apologetics; David Chalmers\'s "hard problem" misappropriated by theists',
        'quote': {'text': 'The soul concept is a hypothesis, and like all hypotheses it must earn its keep. The evidence says it has failed that test.', 'author': 'Patricia Churchland, neurophilosopher'},
    },
    {
        'id': 'pascals-wager',
        'claim': '"Pascal\'s Wager: you should believe in God just in case — the downside of being wrong is infinite."',
        'category': 'reason',
        'icon': '🎲',
        'color': 'var(--reason)',
        'verdict': 'FLAWED',
        'short_rebuttal': 'The wager fails because it ignores thousands of other gods, you cannot choose belief voluntarily, and many theologies condemn insincere belief.',
        'full_rebuttal': 'Pascal\'s Wager has fatal logical flaws. First, the "wrong god" problem: if you bet on Christianity but Allah is the real god, you\'ve earned Islamic damnation. The wager applies equally to every religion ever invented — it gives no guidance on which to choose and leads to paralysis. Second, belief is not a voluntary act — you cannot simply decide to find a proposition credible because it would be advantageous. Third, many theological traditions specifically condemn insincere, transactional faith motivated by self-interest — Pascal\'s bet may itself be the wrong kind of belief. Fourth, an intellectually honest God who rewards genuine inquiry over fearful hedging is equally possible.',
        'evidence': [
            'There have been thousands of mutually exclusive religions with incompatible gods — the wager applies to all equally, offering no rational method of selection.',
            'Many Islamic and Christian theologies explicitly condemn insincere, transactional belief — Pascal\'s strategy may itself guarantee damnation.',
            'Belief is not a voluntary choice — you cannot decide to find a proposition credible; only evidence can produce genuine belief.',
            'A deity who values authentic inquiry over fearful hedging is equally probable — in which case Pascal\'s Wager selects the worst strategy.',
        ],
        'source_claim': 'Blaise Pascal, "Pensées" (1670); common argument in religious apologetics',
        'quote': {'text': 'Pascal\'s Wager is a bet you cannot win, made on a proposition you do not actually believe.', 'author': 'Richard Dawkins · The God Delusion, 2006'},
    },
    {
        'id': 'from-monkeys',
        'claim': '"If evolution is true, why are there still monkeys? Humans couldn\'t have come from monkeys."',
        'category': 'evolution',
        'icon': '🦧',
        'color': 'var(--evolution)',
        'verdict': 'MYTH',
        'short_rebuttal': 'Evolution doesn\'t say humans came from modern monkeys. Humans and chimpanzees share a common ancestor from ~7 million years ago — monkeys are more distantly related still.',
        'full_rebuttal': 'This objection rests on a misunderstanding of how evolution works. Evolution doesn\'t say humans evolved from modern monkeys or modern chimpanzees — that would require the ancestor to disappear. Instead, both lineages descended from a shared common ancestor. The human-chimpanzee common ancestor lived approximately 6–8 million years ago. Both lineages have been evolving independently since then. Modern chimpanzees are our evolutionary cousins, not our parents. Monkeys are even more distantly related — our last common ancestor with monkeys was ~25 million years ago. The question is equivalent to: "If you descended from your grandparents, why do your cousins still exist?"',
        'evidence': [
            'Human-chimpanzee divergence: ~6–8 million years ago, confirmed independently by molecular clocks and the hominid fossil record.',
            'Human and chimpanzee genomes differ by only ~1.2% in single nucleotide substitutions — more similar to each other than horses are to donkeys.',
            'Human-monkey last common ancestor: ~25 million years ago — long before the human lineage existed.',
            'Dozens of intermediate hominid species documented: Sahelanthropus, Orrorin, Ardipithecus, multiple Australopithecus species, all intermediate between the common ancestor and Homo sapiens.',
        ],
        'source_claim': 'Popular confusion; repeated in creationist education materials',
        'quote': {'text': 'We are not the crown of creation. We are one twig on a branching bush — cousin to everything alive.', 'author': 'Stephen Jay Gould, paleontologist'},
    },
    {
        'id': 'abiogenesis',
        'claim': '"Life could not arise from non-life without a creator. Abiogenesis is impossible."',
        'category': 'evolution',
        'icon': '🧪',
        'color': 'var(--evolution)',
        'verdict': 'FLAWED',
        'short_rebuttal': 'Abiogenesis is an active, productive research field. We understand multiple plausible pathways by which chemistry becomes biology — no creator is required.',
        'full_rebuttal': 'The claim misrepresents what science says and ignores 70 years of research. Stanley Miller and Harold Urey showed in 1953 that amino acids — the building blocks of proteins — form spontaneously from simple chemicals (water, methane, ammonia, hydrogen) when an energy source (lightning) is present. Subsequent work found that RNA can both store genetic information AND catalyse chemical reactions (RNA world hypothesis), solving the "chicken and egg" problem of proteins requiring DNA requiring proteins. Lipid bilayers — the membranes that enclose all cells — self-assemble spontaneously in water from fatty acids. Hydrothermal vents provide stable chemical gradients that can drive the formation of complex organic molecules. None of this is "life," but each is a naturalistic, demonstrated step. "We don\'t have every detail yet" is not evidence of a creator — it is the frontier of science.',
        'evidence': [
            'Miller-Urey experiment (1953): amino acids synthesised spontaneously from inorganic chemicals and an energy source in just one week.',
            'RNA world hypothesis: RNA molecules can both encode information (like DNA) and catalyse reactions (like proteins) — solving the chicken-and-egg problem of life\'s origin.',
            'Lipid bilayers (the material of cell membranes) self-assemble spontaneously when fatty acids are placed in water — no instruction needed.',
            'Hydrothermal vents (alkaline, deep-sea, e.g. Lost City field) provide stable pH and chemical gradients that may have driven the first biochemical reactions.',
            'Jack Szostak\'s lab (Harvard) has created protocells — self-replicating RNA inside lipid vesicles — from purely chemical components.',
        ],
        'source_claim': 'Intelligent Design (Michael Behe, Stephen Meyer); creationist apologetics',
        'quote': {'text': 'The probability of life originating from accident is comparable to the probability of the Unabridged Dictionary resulting from an explosion in a printing shop. Except we\'re not arguing for accident — we\'re arguing for chemistry.', 'author': 'adapted from Jack Szostak, Nobel Laureate in Chemistry 2009'},
    },
    {
        'id': 'irreducible-complexity',
        'claim': '"The bacterial flagellum is irreducibly complex — it could not have evolved step by step. This proves a designer."',
        'category': 'evolution',
        'icon': '🔬',
        'color': 'var(--evolution)',
        'verdict': 'MYTH',
        'short_rebuttal': 'The flagellum\'s components are found independently in other biological systems — they evolved from repurposed parts. This was demonstrated in court and in peer-reviewed literature.',
        'full_rebuttal': 'Michael Behe coined "irreducible complexity" in "Darwin\'s Black Box" (1996), claiming the flagellum\'s ~40-protein structure could not function with any parts removed. But "irreducible complexity" doesn\'t mean "couldn\'t have evolved" — it means "can\'t function if you remove parts NOW." Evolution does not require all parts to have always been present: it repurposes, co-opts, and adapts existing systems. The flagellum\'s base, the Type III Secretion System (T3SS), exists independently in many bacteria — it pumps proteins. Evolution could repurpose this "pump" into a "motor." At the 2005 Kitzmiller v. Dover Area School District trial, Behe admitted under oath that his definition of irreducible complexity, strictly applied, would make the immune system irreducibly complex too — and the judge ruled Intelligent Design is not science. Peer review has found no irreducibly complex biological system.',
        'evidence': [
            'The Type III Secretion System (T3SS) shares 10 of the flagellum\'s ~40 proteins and functions independently as a protein pump — evidence of evolutionary co-option, not design from scratch.',
            'Comparative genomics shows flagellum proteins have sequence homologs across bacteria with related functions — a molecular fossil record of evolutionary repurposing.',
            'Kitzmiller v. Dover (2005): U.S. Federal Court ruled Intelligent Design is not science after Behe admitted his standards would also classify the immune system as "irreducibly complex."',
            'No peer-reviewed biological paper has demonstrated a true case of irreducible complexity that could not be explained by evolutionary co-option.',
        ],
        'source_claim': 'Michael Behe, "Darwin\'s Black Box" (1996); Discovery Institute; Intelligent Design movement',
        'quote': {'text': 'Behe\'s claim of irreducible complexity has been refuted by the discovery that every so-called irreducibly complex structure has simpler evolutionary precursors.', 'author': 'Kenneth Miller, cell biologist, Brown University'},
    },
    {
        'id': 'nde-afterlife',
        'claim': '"Near-death experiences prove the soul leaves the body and the afterlife is real."',
        'category': 'reason',
        'icon': '🧠',
        'color': 'var(--reason)',
        'verdict': 'FLAWED',
        'short_rebuttal': 'NDEs are real subjective experiences — but they are fully explained by known neuroscience: oxygen deprivation, REM intrusion, endorphin release, and temporal lobe activity.',
        'full_rebuttal': 'Near-death experiences (NDEs) are genuine, vivid, and often life-changing. No one denies people have them. The question is what they reveal about reality. The naturalistic explanation is strong: (1) Oxygen deprivation to the retina produces a tunnel-of-light effect, exactly matching NDE reports; (2) Ketamine and LSD — which work on specific brain receptors — reliably reproduce NDE phenomenology without any near-death event; (3) Temporal lobe stimulation (Penfield\'s experiments, 1955) produces out-of-body sensations and life reviews on demand; (4) REM intrusion (dream-state elements bleeding into waking) occurs in ~80% of NDEs; (5) The AWARE study (Parnia, 2014) — specifically designed to test whether consciousness leaves the body — found no confirmed cases of accurate out-of-body perception from a placed card that could only be seen from above the operating table.',
        'evidence': [
            'Ketamine at sub-anesthetic doses reliably produces classic NDE phenomenology (tunnel, light, beings, life review) — purely pharmacological, no death required.',
            'Wilder Penfield\'s temporal lobe stimulation experiments (1955): direct brain stimulation produces out-of-body experiences and vivid life reviews on demand, with the patient fully awake.',
            'The AWARE study (Sam Parnia, 2014): of 2,060 cardiac arrest patients, no confirmed case of accurate out-of-body perception of randomly placed hidden images.',
            'Oxygen deprivation to the visual cortex produces the characteristic tunnel-light pattern physiologically — documented in fighter pilots experiencing G-LOC (gravitational loss of consciousness).',
        ],
        'source_claim': 'Pim van Lommel "Consciousness Beyond Life"; Eben Alexander "Proof of Heaven"; religious claims of soul survival',
        'quote': {'text': 'An experience can be profound and meaningful and still be produced by the brain. The brain is the most complex object in the known universe — dismissing its capacity for vivid inner experience as impossible without a soul reflects ignorance of neuroscience, not evidence of a soul.', 'author': 'Susan Blackmore, psychologist and NDE researcher'},
    },
    {
        'id': 'hitler-atheist',
        'claim': '"Hitler was an atheist. Atheism leads to atrocities — the worst crimes in history were committed by atheist regimes."',
        'category': 'reason',
        'icon': '⚠️',
        'color': 'var(--reason)',
        'verdict': 'MYTH',
        'short_rebuttal': 'Hitler explicitly invoked Christianity in his writings and speeches, and never formally left the Catholic Church. The atrocities of communist regimes were caused by authoritarian ideology, not by atheism.',
        'full_rebuttal': 'Hitler was raised Catholic and never formally left the Church. Mein Kampf (1925) contains 27 references to God, multiple invocations of divine providence, and the claim that fighting Jews was "doing the Lord\'s work." His speeches regularly invoked the "Almighty Creator," "Providence," and his divine mission. The Wehrmacht\'s belt buckle read "Gott Mit Uns" (God With Us). The Nazi concordat with the Vatican (1933) was signed during Hitler\'s rise and the Catholic Church never excommunicated him. Stalin and Mao\'s atrocities were committed under Marxist-Leninist ideology — a pseudo-scientific quasi-religion that functioned structurally like religion, with holy texts, infallible leaders, heresies, and purges. These atrocities were not committed in the name of atheism or because of a lack of belief in God — they were committed in the name of ethnic nationalism, Marxist utopianism, and totalitarianism. There is no coherent causal mechanism by which "lack of belief in God" produces genocide. The most peaceful, cooperative, and low-crime societies on Earth today (Scandinavia, Japan, New Zealand) are among the most secular.',
        'evidence': [
            'Mein Kampf (1925): "I am convinced that I am acting as the agent of our Creator. By fighting off the Jews, I am doing the Lord\'s work." (Vol. 1, Ch. 2)',
            'Nazi belt buckle inscription: "Gott Mit Uns" (God With Us) — issued to every soldier in the Wehrmacht.',
            'Concordat between Nazi Germany and the Vatican signed July 20, 1933 — the Catholic Church never excommunicated Hitler.',
            'The Global Peace Index consistently ranks Iceland, Denmark, Ireland, Austria, and New Zealand (all highly secular) among the top 10 most peaceful nations on Earth.',
            'Transparency International\'s Corruption Perceptions Index: 8 of the top 10 least corrupt countries are among the most secular (Denmark, Finland, New Zealand, Sweden, Norway).',
        ],
        'source_claim': 'Christian apologists (Dinesh D\'Souza, William Lane Craig); popular culture; meme-based arguments',
        'quote': {'text': 'You do not need God to be moral. If you cannot determine right from wrong without religion, you have a far more serious problem than a lack of faith.', 'author': 'Penn Jillette, atheist author and magician'},
    },
    {
        'id': 'science-faith',
        'claim': '"Science requires just as much faith as religion — faith in the scientific method, faith in logic, faith in your senses. It\'s all faith at the bottom."',
        'category': 'reason',
        'icon': '🔬',
        'color': 'var(--reason)',
        'verdict': 'MYTH',
        'short_rebuttal': 'Scientific methodology is self-validating through its results — medicine cures, engineering works, physics predicts. Religious faith produces no such independently verifiable results. The word "faith" is being used in two entirely different senses.',
        'full_rebuttal': 'This argument plays on the ambiguity of "faith." Scientific methodology uses trust based on demonstrated reliability: sense-based models generate accurate, testable, independently verifiable predictions. The scientific method has cured diseases, built bridges that don\'t fall, predicted lunar eclipses to the second, and built the internet. These successes are verification, not faith. Religious faith, by contrast, is explicitly defined in Hebrews 11:1 as "the substance of things hoped for, the evidence of things not seen" — belief held in the absence of evidence. The two concepts are not analogous. Scientific confidence is graded, provisional, and revised in the presence of better evidence. Religious faith is often explicitly praised for being unaffected by counter-evidence — the "virtue" of faith is precisely that it doesn\'t yield to evidence. Conflating them requires ignoring this fundamental distinction.',
        'evidence': [
            'Newton\'s law of gravity predicted the return of Halley\'s Comet to within days. General relativity predicted the deflection of light by the Sun, measured and confirmed in 1919.',
            'Germ theory (once considered speculative) was validated by eliminating cholera by cleaning water supplies — a direct test with a direct measurable result.',
            'Scientific trust in senses is provisional and calibrated: science built microscopes, telescopes, and spectrometers precisely to correct and extend what unaided senses can detect.',
            'Religious faith is described within most religious traditions as praiseworthy specifically when maintained against doubt or evidence — the explicit opposite of scientific methodology.',
        ],
        'source_claim': 'Apologetics (C.S. Lewis, Alvin Plantinga, presuppositionalists); popular internet debate',
        'quote': {'text': 'Faith is not a virtue when it substitutes for evidence. It is a cognitive failure dressed as a moral one.', 'author': 'Sam Harris, neuroscientist'},
    },
    {
        'id': 'quantum-god',
        'claim': '"Quantum mechanics proves that consciousness creates reality, or that God exists, or that miracles are scientifically possible."',
        'category': 'cosmology',
        'icon': '⚛️',
        'color': 'var(--cosmology)',
        'verdict': 'MYTH',
        'short_rebuttal': 'Quantum mechanics is a precise mathematical theory about subatomic particles. Its "observer" is any physical interaction — not human consciousness. The leap to consciousness or God is a massive misrepresentation rejected by physicists.',
        'full_rebuttal': 'This claim comes in two forms. First: "The quantum observer collapses the wave function, therefore consciousness creates reality." The "observer" in quantum mechanics is any physical interaction that causes decoherence — a photon hitting a detector, a particle interacting with its environment. It has nothing to do with consciousness or minds. A rock "observing" a quantum system collapses the wave function just as effectively as a physicist. Wojciech Zurek\'s decoherence program shows that quantum measurement arises from entanglement with the environment, not from any special role for consciousness. Second: "Quantum randomness means miracles are scientifically possible." This confuses quantum indeterminacy at subatomic scales with macroscopic events. At macroscopic scales, quantum effects average out — the probability of quantum randomness producing a dead person spontaneously regenerating is not "scientifically possible" — it is so unlikely as to be effectively impossible. Films like "What the Bleep Do We Know" and books by Deepak Chopra deliberately misrepresent quantum mechanics to support mystical claims — a practice physicists have repeatedly condemned.',
        'evidence': [
            'The "observer" in the double-slit experiment can be a detector recording which slit a particle passed through — no consciousness required. Erasing the detector record restores the interference pattern.',
            'Wojciech Zurek\'s decoherence program: wave function collapse arises from quantum entanglement with the environment — consciousness plays no role in the mathematics.',
            'Physicists who have explicitly criticised "quantum consciousness" claims include Richard Feynman, Murray Gell-Mann, Steven Weinberg, and Sean Carroll.',
            'Schrödinger\'s Cat was designed by Schrödinger as a reductio ad absurdum to show how ABSURD it would be if consciousness were required for wave function collapse — apologists have inverted the intended meaning.',
        ],
        'source_claim': 'Deepak Chopra "Quantum Healing"; "What the Bleep Do We Know" (2004); New Age spiritualism; some Christian apologists',
        'quote': {'text': 'Quantum mechanics is not a license to believe whatever you want. It is a very precise theory about very small things, and it implies nothing mystical at the macroscopic level.', 'author': 'Sean Carroll, theoretical physicist, Caltech'},
    },
    {
        'id': 'no-atheists-foxholes',
        'claim': '"There are no atheists in foxholes — when people face death, they turn to God. This proves God is real or that atheism is unsustainable."',
        'category': 'reason',
        'icon': '🎖️',
        'color': 'var(--reason)',
        'verdict': 'MYTH',
        'short_rebuttal': 'The Military Association of Atheists and Freethinkers documents thousands of atheist combat veterans. And even if fear induced belief, this would prove that fear affects cognition — not that God exists.',
        'full_rebuttal': 'This claim is both factually false and logically irrelevant. Factually: the Military Association of Atheists and Freethinkers (MAAF) documents thousands of atheist, agnostic, and non-religious active service members in the U.S. military alone. Pat Tillman, the NFL player killed in Afghanistan who became a national hero, was a committed atheist. Christopher Hitchens maintained his atheism while dying of terminal esophageal cancer, explicitly rejecting any deathbed conversion. Logically: even if fear made people believe in God, this would prove only that stress affects cognition — not that what people believe under stress is true. People under extreme stress also hallucinate, form false memories, and make catastrophically irrational decisions. Terror-induced belief is not a reliable path to truth. The argument commits the genetic fallacy: the circumstances under which a belief arises are not evidence for or against the belief\'s truth.',
        'evidence': [
            'The Military Association of Atheists and Freethinkers (MAAF): documents thousands of non-religious service members and provides chaplain-equivalent support for non-religious military personnel.',
            'Pat Tillman — former NFL player, killed in Afghanistan, decorated national hero — was a committed atheist whose family clashed with the military over attempts to use religious themes at his memorial.',
            'Christopher Hitchens maintained his atheism through terminal cancer, writing about it extensively and explicitly rejecting any deathbed conversion right up to his death in 2011.',
            'The genetic fallacy: the circumstances under which a belief arises say nothing about whether that belief is true.',
        ],
        'source_claim': 'Common religious aphorism; repeated in popular culture and apologetics',
        'quote': {'text': 'The fact that a believer is happier than a skeptic is no more to the point than the fact that a drunk is happier than a sober man.', 'author': 'George Bernard Shaw'},
    },
    {
        'id': 'dna-designer',
        'claim': '"DNA is a code — codes require a coder. The information in DNA proves God designed life."',
        'category': 'evolution',
        'icon': '🧬',
        'color': 'var(--evolution)',
        'verdict': 'FLAWED',
        'short_rebuttal': 'DNA is a chemical molecule, not a human language. It was not "encoded" by a mind — it was selected by physics and evolution. The "code" analogy is a metaphor, not a mechanism.',
        'full_rebuttal': 'The argument commits an analogy error. Human codes are designed because we observe designers making them — but the analogy says nothing about biology unless you first assume DNA is relevantly similar to human language, which is the very question at issue. DNA is a chemical polymer. The "code" is the biochemical relationship between nucleotide triplets and amino acids — a relationship that arose via chemical selection. In the RNA world, the earliest genetic molecules were short RNA chains that replicated and competed chemically, with no mind involved. The genetic code is also not unique — at least 26 variations of the "standard" code exist in different organisms, exactly what evolutionary divergence predicts and not what a single act of creation would. Furthermore, DNA contains enormous amounts of junk, broken genes (pseudogenes), and viral insertions — not the signature of an efficient coder but exactly the signature of undirected evolutionary accumulation.',
        'evidence': [
            'At least 26 variant genetic codes exist across different organisms — evolution predicts divergence; a single designer would produce a single optimal code.',
            'The human genome is ~8% ancient viral insertions (endogenous retroviruses) — broken, non-functional, and at identical locations in our closest primate relatives: a signature of evolutionary history, not design.',
            'Pseudogenes: non-functional broken copies of genes (e.g., GULO pseudogene for vitamin C synthesis, present at the same chromosomal location in humans and chimpanzees) — evidence of common descent, not design.',
            'Laboratory evolution (LTEE — Lenski\'s 35+ year E. coli experiment) has produced new genetic complexity and even new metabolic capabilities through undirected mutation and selection alone.',
        ],
        'source_claim': 'Intelligent Design (William Dembski "No Free Lunch"; Stephen Meyer "Signature in the Cell")',
        'quote': {'text': 'The genome of every organism is a palimpsest — overwritten, corrupted, patched, and reused. It looks nothing like designed code. It looks exactly like accumulated evolutionary history.', 'author': 'Richard Dawkins, evolutionary biologist'},
    },
    {
        'id': 'universe-hostile',
        'claim': '"The universe was designed for life — everything is perfectly set up for us to exist."',
        'category': 'cosmology',
        'icon': '🌌',
        'color': 'var(--cosmology)',
        'verdict': 'MYTH',
        'short_rebuttal': 'The universe is overwhelmingly hostile to life by every measure. Life exists in a tiny corner of one planet out of trillions, in a universe 13.8 billion years old that existed for 9 billion years before Earth formed.',
        'full_rebuttal': 'The "designed for life" claim collapses when you look at the actual numbers. The observable universe contains ~2 trillion galaxies, ~10²⁴ stars, and ~93 billion light-years of space. Of all that space, life is confirmed on exactly one planet — a pale blue dot orbiting one ordinary star, in one ordinary galaxy. The universe existed for 9.1 billion years before Earth even formed. 99.9999% of the universe\'s volume is lethal — extreme cold, radiation, vacuum, or gravitational tidal forces. 99.9% of all species that ever lived on Earth are extinct, most before any human existed to observe them. Five mass extinctions killed the majority of all life. If the universe was designed for us, the designer wasted 99.99999% of the effort and waited 9 billion years to begin. This is not what a caring designer would do. It is exactly what an indifferent physical universe would look like.',
        'evidence': [
            'The observable universe: 93 billion light-years across, ~2 trillion galaxies, ~10²⁴ stars — life confirmed on 1 planet.',
            'The universe existed for 9.1 billion years before Earth formed — not one known instance of life for 9 billion years.',
            '99.9% of all species ever to live on Earth are extinct, mostly before any human existed.',
            'The surface area of Earth is ~510 million km² — of that, ~71% ocean, ~29% land. Life-sustaining continental surface has existed for a fraction of Earth\'s 4.54 billion year history.',
            'Nearest confirmed habitable-zone exoplanet: ~4.2 light years away (Proxima b) — unreachable with current technology, unknown if habitable.',
        ],
        'source_claim': 'Anthropic teleological arguments; fine-tuning apologetics; Intelligent Design',
        'quote': {'text': 'The universe is a deadly place. We exist in a thin biosphere on one planet around one star among hundreds of billions in a galaxy that is one of two trillion. This is not a universe designed for life — this is life clinging to existence in a universe that does not notice it.', 'author': 'Neil deGrasse Tyson, astrophysicist'},
    },
    {
        'id': 'prayer-heals',
        'claim': '"Prayer heals — there are documented medical miracles and clinical evidence that prayer works."',
        'category': 'reason',
        'icon': '🙏',
        'color': 'var(--reason)',
        'verdict': 'MYTH',
        'short_rebuttal': 'The largest randomized controlled trial of intercessory prayer (STEP, 2006) found no benefit — and patients who knew they were being prayed for had worse outcomes.',
        'full_rebuttal': 'This is one of the most directly testable religious claims in existence — and it has been tested. The STEP study (Study of the Therapeutic Effects of Intercessory Prayer, Benson et al., 2006, American Heart Journal) randomized 1,802 cardiac bypass patients into three groups: prayer/told, prayer/not told, no prayer/not told. Result: no statistically significant benefit from prayer in any group, and patients who knew they were being prayed for had significantly more complications (59% vs 52%), possibly from "performance anxiety" (knowing others thought they needed prayer). Cochrane systematic reviews pooling dozens of prayer studies find no reliable clinical benefit. "Miraculous" recoveries are rare but real — they represent the natural tail of statistical distributions of outcomes, placebo effects, diagnostic errors, and the well-documented capacity of the immune system to produce remarkable recoveries. No prayer intervention has ever outperformed placebo in a properly blinded trial.',
        'evidence': [
            'STEP study (Benson et al., 2006, n=1,802): no benefit from intercessory prayer; patients told they were being prayed for had MORE complications (59% vs 52%).',
            'Cochrane systematic reviews of prayer studies: no statistically reliable health benefit found across pooled controlled trials.',
            '"Miraculous" recoveries occur at rates consistent with known base rates of spontaneous remission, late-stage immune responses, and diagnostic revision.',
            'Every prayer study showing positive effects has failed to replicate — hallmark of a chance finding, not a real effect.',
        ],
        'source_claim': 'Faith healing; religious testimonials; prosperity gospel; Catholic miracle-verification processes',
        'quote': {'text': 'Prayer has been tested in clinical trials and failed. If prayer worked, it would appear in the Cochrane database of evidence-based medicine. It does not.', 'author': 'Edzard Ernst, emeritus professor of complementary medicine, University of Exeter'},
    },
]
