GLOSSARY = [
    {'term': 'Singularity', 'definition': 'A point where General Relativity\'s equations break down, predicting infinite density. Not a physical object — a sign the theory is incomplete at that scale.'},
    {'term': 'Entropy', 'definition': 'A measure of disorder, or equivalently, the number of microscopic configurations matching a given macroscopic state. The Second Law of Thermodynamics says it tends to increase over time in a closed system.'},
    {'term': 'Quantum Fluctuation', 'definition': 'A temporary, random change in energy at a point in space, permitted by the Heisenberg uncertainty principle even in a vacuum.'},
    {'term': 'Virtual Particle', 'definition': 'A short-lived particle that exists due to quantum field fluctuations, allowed to "borrow" energy briefly under the uncertainty principle. Their effects are real and measurable (e.g. the Lamb shift).'},
    {'term': 'Decoherence', 'definition': 'The process by which a quantum system loses its superposition and behaves classically due to interaction with its environment.'},
    {'term': 'Inflation (Cosmic)', 'definition': 'A theorized period of exponential expansion in the first fraction of a second after the Big Bang, explaining the universe\'s flatness and uniformity.'},
    {'term': 'No-Boundary Proposal', 'definition': 'Hartle and Hawking\'s 1983 model in which the universe has no temporal beginning — time emerges smoothly from quantum geometry, like there is no "edge" to ask about.'},
    {'term': 'Fine-Tuning', 'definition': 'The observation that physical constants fall within ranges allowing complex chemistry. Contested as evidence for design — alternative explanations include anthropic selection and multiverse models.'},
    {'term': 'Natural Selection', 'definition': 'The process by which organisms with heritable traits better suited to their environment tend to survive and reproduce more, driving evolutionary change.'},
    {'term': 'Cosmic Microwave Background (CMB)', 'definition': 'The faint afterglow radiation left over from 380,000 years after the Big Bang, observable in all directions.'},
    {'term': 'Dark Matter', 'definition': 'An unidentified form of matter inferred from its gravitational effects, which does not interact with light. Makes up about 27% of the universe.'},
    {'term': 'Dark Energy', 'definition': 'A mysterious force or property of space causing the expansion of the universe to accelerate. Makes up about 68% of the universe.'},
    {'term': 'Many-Worlds Interpretation', 'definition': 'A reading of quantum mechanics in which every measurement outcome occurs, each in a separate, decohering branch of reality, rather than collapsing to one.'},
    {'term': 'Great Filter', 'definition': 'A hypothesized bottleneck — biological or sociological — that makes the jump from simple chemistry to a detectable interstellar civilization extremely rare, proposed to explain the Fermi Paradox.'},
    {'term': 'Anthropic Principle', 'definition': 'The observation that any universe we can observe must, by definition, be one compatible with the existence of observers — used to explain apparent fine-tuning without invoking design.'},
    {'term': 'Compatibilism', 'definition': 'The view that free will is compatible with physical determinism: acting according to your own reasons and character counts as free, even though those are themselves products of a physical brain.'},
    {'term': 'Theodicy', 'definition': 'A theological attempt to explain why a benevolent, omnipotent God would permit the existence of evil and suffering.'},
    {'term': 'Big Bounce', 'definition': 'A model in Loop Quantum Cosmology in which the universe\'s expansion was preceded by the gravitational collapse and "bounce" of a previous contracting universe, replacing the classical singularity.'},
    {'term': 'Casimir Effect', 'definition': 'A measurable attractive force between two uncharged conducting plates in a vacuum, caused by restricted virtual particle modes between them — direct evidence the quantum vacuum is not empty.'},
    {'term': 'Nucleosynthesis', 'definition': 'The process by which heavier atomic nuclei are formed, either in the first minutes after the Big Bang (light elements) or inside stars and supernovae (heavier elements).'},
]

BOOKS = [
    {'title': 'A Brief History of Time', 'author': 'Stephen Hawking', 'year': 1988, 'why': 'The classic accessible introduction to cosmology, black holes, and the origin of the universe — including Hawking\'s evolving views on the Big Bang.'},
    {'title': 'The Grand Design', 'author': 'Stephen Hawking & Leonard Mlodinow', 'year': 2010, 'why': 'Hawking\'s explicit argument that the universe can create itself from nothing, with no need for a creator, grounded in M-theory and quantum cosmology.'},
    {'title': 'Cosmos', 'author': 'Carl Sagan', 'year': 1980, 'why': 'The definitive work of scientific wonder — a tour of the universe written with reverence for evidence over mythology.'},
    {'title': 'The Demon-Haunted World', 'author': 'Carl Sagan', 'year': 1995, 'why': 'A masterclass in skepticism and the scientific method as a tool against pseudoscience and superstition.'},
    {'title': 'A Universe from Nothing', 'author': 'Lawrence Krauss', 'year': 2012, 'why': 'A direct, physics-based answer to "why is there something rather than nothing," addressing the cosmological argument for God.'},
    {'title': 'God: The Failed Hypothesis', 'author': 'Victor Stenger', 'year': 2007, 'why': 'Treats God\'s existence as a testable scientific hypothesis and examines it against cosmological and physical evidence.'},
    {'title': 'The God Delusion', 'author': 'Richard Dawkins', 'year': 2006, 'why': 'The most widely read modern case against theism, covering evolutionary biology, philosophy, and the psychology of belief.'},
    {'title': 'The Selfish Gene', 'author': 'Richard Dawkins', 'year': 1976, 'why': 'A foundational work explaining evolution from the gene\'s-eye view, and the origin of the "meme" concept.'},
    {'title': 'God Is Not Great', 'author': 'Christopher Hitchens', 'year': 2007, 'why': 'A sweeping historical and moral critique of organized religion\'s claims and consequences.'},
    {'title': 'Breaking the Spell', 'author': 'Daniel Dennett', 'year': 2006, 'why': 'Applies evolutionary and cognitive science to explain why religious belief is so widespread, treating religion as a natural phenomenon.'},
    {'title': 'Free Will', 'author': 'Sam Harris', 'year': 2012, 'why': 'A short, sharp argument that neuroscience is incompatible with the libertarian free will most religious morality depends on.'},
    {'title': 'Why Evolution Is True', 'author': 'Jerry Coyne', 'year': 2009, 'why': 'A clear, evidence-dense case for evolution by natural selection, built for readers encountering creationist objections.'},
    {'title': 'Lost in Math', 'author': 'Sabine Hossenfelder', 'year': 2018, 'why': 'A rigorous, skeptical look at untestable physics speculation — the same epistemic standards applied throughout this app.'},
    {'title': 'Religion Explained', 'author': 'Pascal Boyer', 'year': 2001, 'why': 'The foundational text of the cognitive science of religion — why human brains generate supernatural belief.'},
    {'title': 'The Big Picture', 'author': 'Sean Carroll', 'year': 2016, 'why': 'A physicist\'s account of how meaning, morality, and purpose can exist in a purely naturalistic universe with no creator.'},
]

ON_THIS_DAY = [
    {'date': '01-03', 'event': 'Einstein\'s letter to Eric Gutkind — explicitly rejecting belief in a personal God and calling the Bible "primitive legends" — was written on this day in 1954.'},
    {'date': '01-07', 'event': 'Galileo Galilei discovered the four largest moons of Jupiter on this day in 1610, undermining the geocentric model central to Church doctrine.'},
    {'date': '01-27', 'event': 'Wolfgang Pauli was born on this day in 1900 — formulator of the exclusion principle, foundational to all of atomic structure and chemistry.'},
    {'date': '02-12', 'event': 'Charles Darwin was born on this day in 1809 — the man who showed that the staggering diversity of life requires no designer, only time and selection.'},
    {'date': '02-15', 'event': 'Galileo Galilei was born on this day in 1564 — tried by the Roman Inquisition for asserting the Earth orbits the Sun.'},
    {'date': '02-19', 'event': 'Nicolaus Copernicus was born on this day in 1473 — his heliocentric model began the dismantling of the Earth-centered, human-centered cosmos.'},
    {'date': '03-14', 'event': 'Albert Einstein was born on this day in 1879. Stephen Hawking died on this very same day in 2018 — a striking coincidence linking two of the greatest minds to challenge supernatural explanations of the cosmos.'},
    {'date': '04-12', 'event': 'Yuri Gagarin became the first human in space on this day in 1961, looking back at Earth from orbit and reporting no sign of heaven.'},
    {'date': '04-25', 'event': 'James Watson and Francis Crick\'s paper describing the double-helix structure of DNA was published on this day in 1953.'},
    {'date': '05-24', 'event': 'The first long-distance telegraph message was sent on this day in 1844 — "What hath God wrought" — ironically inaugurating an age of instantaneous, evidence-based global communication.'},
    {'date': '06-28', 'event': 'Henrietta Leavitt\'s period-luminosity relation for variable stars, published in works around this time, became the key that let Hubble measure the size and expansion of the universe.'},
    {'date': '07-20', 'event': 'Apollo 11 landed on the Moon on this day in 1969 — humans, made of stardust, walking on another world through reason and engineering, not prayer.'},
    {'date': '08-06', 'event': 'The Mars Curiosity rover landed on this day in 2012, beginning over a decade of searching for evidence of past life using pure chemistry and physics.'},
    {'date': '09-12', 'event': 'The Lascaux cave paintings were discovered on this day in 1940 — direct evidence of the cognitive revolution and symbolic thought tens of thousands of years before any scripture.'},
    {'date': '09-28', 'event': 'Darwin\'s "On the Origin of Species" went on sale in London bookshops on this day in 1859, selling out on its first day.'},
    {'date': '10-04', 'event': 'Sputnik 1, the first artificial satellite, launched on this day in 1957 — the opening move of the Space Age.'},
    {'date': '10-24', 'event': 'A typical estimate for the age of the Earth following Bishop Ussher\'s 17th-century chronology placed creation around this time of year in 4004 BCE — radiometric dating now places Earth\'s actual age at 4.54 billion years, a discrepancy of roughly 654 million-fold.'},
    {'date': '11-24', 'event': 'Charles Darwin\'s "On the Origin of Species" was first published on this day in 1859.'},
    {'date': '11-25', 'event': 'Einstein presented the field equations of General Relativity to the Prussian Academy of Sciences on this day in 1915.'},
    {'date': '12-14', 'event': 'Max Planck presented his quantum hypothesis to the German Physical Society on this day in 1900, founding quantum mechanics.'},
    {'date': '12-25', 'event': 'On this day, billions celebrate a nativity story with direct narrative parallels to older Egyptian (Horus), Persian (Mithras), and Roman solstice traditions — a useful reminder that mythological motifs are recycled across cultures, not uniquely revealed.'},
]

SPACE_EVENTS = [
    {
        'name': 'Mercury at Greatest Eastern Elongation',
        'date': '2026-07-04',
        'category': 'planet',
        'icon': '☿',
        'description': 'Mercury reaches its greatest angular distance east of the Sun, making it visible low on the western horizon just after sunset. A rare chance to spot the innermost planet with the naked eye.',
        'tip': 'Look west just after sunset from a location with a clear horizon. Mercury will appear as a bright star very low in the sky. Binoculars help.',
    },
    {
        'name': 'Total Solar Eclipse',
        'date': '2026-08-12',
        'category': 'eclipse',
        'icon': '🌑',
        'description': 'A total solar eclipse visible from Iceland, the Faroe Islands, northern Spain, parts of North Africa, and across the Indian Ocean. Totality lasts up to 2 minutes 18 seconds — the Moon\'s shadow sweeping across the Earth at over 1,000 km/h.',
        'tip': 'NEVER look at the Sun without certified ISO 12312-2 eclipse glasses. Only during totality is it safe to look with the naked eye — and only then can you see the corona.',
        'fact': 'Einstein\'s General Relativity was first confirmed during a total solar eclipse in 1919 by measuring how the Sun\'s gravity bends starlight — exactly as Einstein predicted.',
    },
    {
        'name': 'Perseid Meteor Shower Peak',
        'date': '2026-08-12',
        'category': 'meteor',
        'icon': '☄️',
        'description': 'One of the year\'s finest meteor showers, producing up to 100 meteors per hour at peak. Caused by Earth passing through the debris trail left by Comet 109P/Swift-Tuttle — particles shed thousands of years ago, now vaporizing in our atmosphere at 59 km/s.',
        'tip': 'Best viewed after midnight, facing northeast. No telescope needed — just dark skies, a reclining chair, and patience. Let your eyes adjust for 20 minutes.',
    },
    {
        'name': 'Jupiter at Opposition',
        'date': '2026-09-26',
        'category': 'planet',
        'icon': '🪐',
        'description': 'Jupiter reaches opposition — directly opposite the Sun from Earth\'s perspective — making it the brightest object in the night sky besides the Moon. At opposition, Jupiter is closest to Earth and fully illuminated.',
        'tip': 'Even binoculars reveal Jupiter\'s four Galilean moons: Io, Europa, Ganymede, and Callisto — the same moons Galileo first observed in January 1610, overthrowing the geocentric universe.',
    },
    {
        'name': 'Orionid Meteor Shower Peak',
        'date': '2026-10-21',
        'category': 'meteor',
        'icon': '☄️',
        'description': 'The Orionids produce up to 20 meteors per hour, originating from debris left by Halley\'s Comet on its last two passes. These particles were shed from the comet perhaps thousands of years ago.',
        'tip': 'Best viewed after midnight, looking toward the constellation Orion. Meteors radiate from near Betelgeuse but appear all across the sky.',
    },
    {
        'name': 'Leonid Meteor Shower Peak',
        'date': '2026-11-17',
        'category': 'meteor',
        'icon': '☄️',
        'description': 'The Leonids originate from debris of Comet 55P/Tempel-Tuttle. Every 33 years they produce spectacular storms — in 1833, observers reported tens of thousands of meteors per hour, an event that helped establish the scientific study of meteor showers.',
        'tip': 'Best viewed in the pre-dawn hours. The radiant point rises in the east around midnight in the constellation Leo.',
    },
    {
        'name': 'Geminid Meteor Shower Peak',
        'date': '2026-12-13',
        'category': 'meteor',
        'icon': '☄️',
        'description': 'The Geminids are unique: caused by the asteroid 3200 Phaethon, not a comet. They produce up to 120 multicolored meteors per hour — faster and more varied than most showers. One of the most reliable of the year.',
        'tip': 'The Geminids are visible as early as 9–10 PM, making them more accessible than most showers. Look for the radiant near the star Castor in Gemini.',
    },
    {
        'name': 'Ursid Meteor Shower Peak',
        'date': '2026-12-22',
        'category': 'meteor',
        'icon': '☄️',
        'description': 'A minor but reliable shower coinciding with the winter solstice. Originates from debris of Comet 8P/Tuttle. Produces about 10 meteors per hour from a radiant near the Little Dipper (Ursa Minor).',
        'tip': 'Best observed after midnight from dark, northern-hemisphere sites. The winter solstice marks Earth\'s axial tilt relative to the Sun — no deity required.',
    },
]

MEDIA_PICKS = {
    'podcasts': [
        {
            'name': 'Mindscape',
            'host': 'Sean Carroll',
            'description': 'A theoretical physicist at Caltech interviews scientists, philosophers, and thinkers about the deep nature of reality — from quantum mechanics to consciousness, the arrow of time, and what mathematics is.',
            'icon': '🧠',
            'tags': ['Physics', 'Philosophy', 'Cosmology'],
        },
        {
            'name': 'StarTalk Radio',
            'host': 'Neil deGrasse Tyson',
            'description': 'Astrophysics meets pop culture. Tyson makes the cosmos accessible through humor, celebrity guests, and relentless enthusiasm for evidence-based thinking about our place in the universe.',
            'icon': '🌟',
            'tags': ['Astrophysics', 'Space', 'Pop Culture'],
        },
        {
            'name': 'Making Sense',
            'host': 'Sam Harris',
            'description': 'Conversations about consciousness, free will, morality, rationality, and the limits of religious thinking — grounded in neuroscience, philosophy, and a commitment to evidence over dogma.',
            'icon': '🎙️',
            'tags': ['Philosophy', 'Neuroscience', 'Rationalism'],
        },
        {
            'name': 'The Joy of Why',
            'host': 'Steven Strogatz',
            'description': 'A Cornell mathematician explores the most fundamental questions in science and mathematics — why the universe seems structured by math, what infinity means, and whether we are alone.',
            'icon': '➕',
            'tags': ['Mathematics', 'Physics', 'Philosophy'],
        },
        {
            'name': 'Radiolab',
            'host': 'Jad Abumrad & Robert Krulwich',
            'description': 'Investigative science storytelling that makes biology, physics, and philosophy emotionally resonant. Some of the finest science audio journalism ever produced.',
            'icon': '🔬',
            'tags': ['Biology', 'Philosophy', 'Science Stories'],
        },
        {
            'name': 'Daniel and Jorge Explain the Universe',
            'host': 'Daniel Whiteson & Jorge Cham',
            'description': 'A particle physicist and a cartoonist tackle the biggest open questions in physics: dark matter, dark energy, string theory, the Higgs boson, and the multiverse.',
            'icon': '⚛️',
            'tags': ['Particle Physics', 'Dark Matter', 'Multiverse'],
        },
    ],
    'youtube': [
        {
            'name': 'Veritasium',
            'creator': 'Derek Muller',
            'description': 'Beautifully produced deep dives into physics, mathematics, and the history of science. Muller holds a PhD in physics education research and it shows — no content is oversimplified.',
            'icon': '🎯',
            'tags': ['Physics', 'Mathematics', 'History of Science'],
        },
        {
            'name': 'PBS Space Time',
            'creator': 'PBS Digital Studios',
            'description': 'Graduate-level astrophysics and cosmology presented clearly and rigorously. The most intellectually demanding popular science channel on YouTube — no dumbing down, ever.',
            'icon': '🌌',
            'tags': ['Cosmology', 'Quantum Mechanics', 'Relativity'],
        },
        {
            'name': 'Kurzgesagt – In a Nutshell',
            'creator': 'Kurzgesagt',
            'description': 'Stunning animations explaining everything from the Big Bang to existential risk. Scientifically reviewed by experts and emotionally powerful — the best science animation channel by far.',
            'icon': '🐦',
            'tags': ['Cosmology', 'Biology', 'Future of Humanity'],
        },
        {
            'name': 'Cool Worlds',
            'creator': 'David Kipping',
            'description': 'A Columbia University astronomer explores exoplanets, the search for extraterrestrial life, the Fermi Paradox, and the possibility of interstellar travel — with genuine academic rigor.',
            'icon': '🌍',
            'tags': ['Exoplanets', 'Fermi Paradox', 'Astrobiology'],
        },
        {
            'name': 'SciShow Space',
            'creator': 'Complexly',
            'description': 'Well-sourced, rapid updates on space science news, missions, and discoveries. The ideal channel for staying current on what\'s actually happening in planetary science and astronomy.',
            'icon': '🚀',
            'tags': ['Space News', 'Missions', 'Astronomy'],
        },
        {
            'name': 'History of the Universe',
            'creator': 'History of the Universe',
            'description': 'Cinematic documentary-style videos tracing the complete history of the cosmos from the Big Bang to the far future — narrated with scientific precision and beautiful CGI.',
            'icon': '📽️',
            'tags': ['Cosmology', 'Timeline', 'Big Bang'],
        },
    ],
    'documentaries': [
        {
            'name': 'Cosmos: A Spacetime Odyssey',
            'year': 2014,
            'host': 'Neil deGrasse Tyson',
            'description': 'The definitive modern successor to Sagan\'s original Cosmos. 13 episodes covering the history of science, the scale of the universe, and humanity\'s hard-won understanding of our place in it.',
            'icon': '🔭',
            'tags': ['Cosmology', 'History of Science', 'Must Watch'],
        },
        {
            'name': 'The Fabric of the Cosmos',
            'year': 2011,
            'host': 'Brian Greene',
            'description': 'Based on Brian Greene\'s bestselling book. Four episodes exploring the nature of space, time, quantum reality, and the multiverse — presented with exceptional clarity and visual imagination.',
            'icon': '🧶',
            'tags': ['Quantum Physics', 'Space-Time', 'Multiverse'],
        },
        {
            'name': 'Particle Fever',
            'year': 2013,
            'host': 'Documentary',
            'description': 'An intimate inside look at the discovery of the Higgs boson at CERN. Six physicists experience firsthand what may be the most important scientific discovery of the 21st century.',
            'icon': '⚡',
            'tags': ['Particle Physics', 'CERN', 'Higgs Boson'],
        },
        {
            'name': 'Horizon: What Is Reality?',
            'year': 2011,
            'host': 'BBC',
            'description': 'A BBC Horizon documentary exploring whether reality is mathematical, whether the universe might be a simulation, and what quantum mechanics tells us about the nature of existence itself.',
            'icon': '❓',
            'tags': ['Quantum Mechanics', 'Philosophy', 'Reality'],
        },
    ],
}
