SCIENTISTS = [
    {
        'id': 'einstein',
        'name': 'Albert Einstein',
        'emoji': '🧮',
        'field': 'Theoretical Physics',
        'years': '1879 — 1955',
        'stance': 'agnostic / spinozist',
        'color': '#fbbf24',
        'known_for': 'Special & General Relativity, E=mc², photoelectric effect, Nobel Prize 1921',
        'quote': 'The word God is for me nothing more than the expression and product of human weaknesses, and the Bible a collection of honourable but still primitive legends which are nevertheless pretty childish.',
        'quote_source': 'Letter to Eric Gutkind, January 3, 1954 — sold at auction for $2.9 million',
        'bio': 'The most iconic scientist who ever lived — and one of the most misquoted on religion. Einstein explicitly and repeatedly denied believing in a personal God, heaven, prayer, or afterlife. His "God" was Spinoza\'s — a poetic metaphor for the rational order of nature, nothing supernatural. The viral quote "The more I study science, the more I believe in God" was never said by him. His real words, in his own handwriting, are devastating to theology.',
        'tags': ['Physics', 'Relativity', 'Nobel Laureate', 'Agnostic'],
        'extra_quotes': [
            'I do not believe in a personal God and I have never denied this but have expressed it clearly. If something is in me which can be called religious then it is the unbounded admiration for the structure of the world so far as our science can reveal it.',
            'A man\'s ethical behaviour should be based effectually on sympathy, education, and social ties — no religious basis is necessary. Man would indeed be in a poor way if he had to be restrained by fear of punishment and hope of reward after death.',
            'I cannot imagine a God who rewards and punishes the objects of his creation, whose purposes are modelled after our own — a God, in short, who is but a reflection of human frailty.',
            'The religion of the future will be a cosmic religion. It should transcend personal God and avoid dogma and theology. Buddhism answers this description. If there is any religion that could cope with modern scientific needs, it would be Buddhism.',
        ],
    },
    {
        'id': 'hawking',
        'name': 'Stephen Hawking',
        'emoji': '🌌',
        'field': 'Theoretical Physics & Cosmology',
        'years': '1942 — 2018',
        'stance': 'atheist',
        'color': '#00d4ff',
        'known_for': 'Black hole radiation, A Brief History of Time, No-Boundary Proposal',
        'quote': 'There is no God. No one created the universe and no one directs our fate. This leads me to a profound realisation that there probably is no heaven and no afterlife either.',
        'quote_source': 'The Guardian, 2011',
        'bio': 'Perhaps the most celebrated scientist of his generation, Hawking spent his career dismantling the notion that the universe required a creator. His Hartle-Hawking no-boundary proposal shows the universe can be self-contained with no beginning — and thus no need for a creator. He called God "a fairy story for people afraid of the dark."',
        'tags': ['Physics', 'Cosmology', 'Black Holes'],
        'extra_quotes': [
            'Before we understood science, it was natural to believe that God created the universe, but now science offers a more convincing explanation.',
            'I regard the brain as a computer which will stop working when its components fail. There is no heaven or afterlife for broken-down computers; that is a fairy story for people afraid of the dark.',
            'We are just an advanced breed of monkeys on a minor planet of a very average star. But we can understand the Universe. That makes us something very special.',
        ],
    },
    {
        'id': 'krauss',
        'name': 'Lawrence Krauss',
        'emoji': '⚛️',
        'field': 'Theoretical Physics & Cosmology',
        'years': '1954 — present',
        'stance': 'atheist',
        'color': '#a855f7',
        'known_for': 'A Universe from Nothing, The Physics of Star Trek, science communication',
        'quote': 'Every atom in your body came from a star that exploded. And the atoms in your left hand probably came from a different star than your right hand. It really is the most poetic thing I know about physics.',
        'quote_source': 'A Universe from Nothing, 2012',
        'bio': 'Krauss is one of the most forceful scientific voices against religion and for atheism. His book "A Universe from Nothing" directly addresses the cosmological argument for God — showing how quantum mechanics allows the universe to arise from a quantum vacuum, requiring no creator. He argues science has made God not just unnecessary but incoherent.',
        'tags': ['Physics', 'Cosmology', 'Atheism'],
        'extra_quotes': [
            'The universe is the way it is, whether we like it or not. The existence of God is not required by the laws of physics.',
            'Forget Jesus. The stars died so that you could be here today.',
            'Science is the only truly global human endeavour, and our future depends on it.',
        ],
    },
    {
        'id': 'dirac',
        'name': 'Paul Dirac',
        'emoji': '⚡',
        'field': 'Theoretical Physics & Quantum Mechanics',
        'years': '1902 — 1984',
        'stance': 'atheist',
        'color': '#f97316',
        'known_for': 'Dirac equation, prediction of antimatter, quantum field theory, Nobel Prize 1933',
        'quote': 'If we are honest — and scientists have to be — we must admit that religion is a jumble of false assertions, with no basis in reality. The very idea of God is a product of the human imagination.',
        'quote_source': 'Conference discussion, Brussels, 1927 (reported by Heisenberg)',
        'bio': 'One of the greatest physicists who ever lived, Dirac formulated the equation predicting antimatter and helped found quantum field theory. He was famously blunt about religion — in a 1927 discussion with fellow physicists, he gave a devastating critique of all theistic belief that left Heisenberg speechless. He viewed religion as incompatible with scientific honesty.',
        'tags': ['Quantum Physics', 'Nobel Laureate', 'Antimatter'],
        'extra_quotes': [
            'The aim of science is to make difficult things understandable in a simpler way; the aim of poetry is to state simple things in an incomprehensible way. The two are incompatible.',
            'In science one tries to tell people, in such a way as to be understood by everyone, something that no one ever knew before. But in poetry, it\'s the exact opposite.',
            'God used beautiful mathematics in creating the world — but I do not believe in God.',
        ],
    },
    {
        'id': 'feynman',
        'name': 'Richard Feynman',
        'emoji': '🎯',
        'field': 'Theoretical Physics & Quantum Electrodynamics',
        'years': '1918 — 1988',
        'stance': 'agnostic / atheist',
        'color': '#fbbf24',
        'known_for': 'Quantum Electrodynamics (QED), Feynman diagrams, Nobel Prize 1965',
        'quote': 'I think it\'s much more interesting to live not knowing than to have answers which might be wrong. I have approximate answers and possible beliefs and different degrees of certainty about different things, but I\'m not absolutely sure of anything.',
        'quote_source': 'The Pleasure of Finding Things Out, 1981',
        'bio': 'Nobel laureate and arguably the most charismatic physicist of the 20th century, Feynman refused to accept anything on faith — including religion. He was openly critical of religious thinking, calling it incompatible with scientific culture. His principle: "The first principle is that you must not fool yourself — and you are the easiest person to fool."',
        'tags': ['Quantum Physics', 'Nobel Laureate', 'QED'],
        'extra_quotes': [
            'Religion is a culture of faith; science is a culture of doubt.',
            'The first principle is that you must not fool yourself — and you are the easiest person to fool.',
            'I would rather have questions that can\'t be answered than answers that can\'t be questioned.',
            'Science is the belief in the ignorance of experts.',
        ],
    },
    {
        'id': 'sagan',
        'name': 'Carl Sagan',
        'emoji': '🔭',
        'field': 'Astronomy, Astrophysics & Science Communication',
        'years': '1934 — 1996',
        'stance': 'agnostic',
        'color': '#22c55e',
        'known_for': 'Cosmos series, Pale Blue Dot, Contact, popularising science',
        'quote': 'The cosmos is all that is, or ever was, or ever will be. Our planet is a lonely speck in the great enveloping cosmic dark. In our obscurity, in all this vastness, there is no hint that help will come from elsewhere to save us from ourselves.',
        'quote_source': 'Cosmos: A Personal Voyage, 1980',
        'bio': 'Sagan was the greatest science communicator of the 20th century and a lifelong agnostic who found more wonder in science than in any religion. His "Pale Blue Dot" speech is one of the most powerful secular humanist statements ever made. He argued that the universe\'s scale makes human religious pretensions absurd.',
        'tags': ['Astronomy', 'Agnostic', 'Science Communication'],
        'extra_quotes': [
            'We are a way for the cosmos to know itself.',
            'An atheist is someone who is certain that God does not exist. I\'m not certain. I\'m an agnostic.',
            'For me, it is far better to grasp the universe as it really is than to persist in delusion, however satisfying and reassuring.',
            'Somewhere, something incredible is waiting to be known.',
        ],
    },
    {
        'id': 'dawkins',
        'name': 'Richard Dawkins',
        'emoji': '🧬',
        'field': 'Evolutionary Biology & Ethology',
        'years': '1941 — present',
        'stance': 'atheist',
        'color': '#22c55e',
        'known_for': 'The Selfish Gene, The God Delusion, meme theory, evolution',
        'quote': 'The universe we observe has precisely the properties we should expect if there is, at the bottom, no design, no purpose, no evil, no good — nothing but blind, pitiless indifference.',
        'quote_source': 'River Out of Eden, 1995',
        'bio': 'The world\'s most famous living atheist, Dawkins spent his career showing that Darwinian evolution eliminates the need for any designer. "The God Delusion" sold over 3 million copies. His concept of the "meme" extended evolutionary thinking to culture. He views religion as a dangerous delusion that humanity must grow out of.',
        'tags': ['Biology', 'Evolution', 'Atheism'],
        'extra_quotes': [
            'Faith is the great cop-out, the great excuse to evade the need to think and evaluate evidence.',
            'We are all atheists about most of the gods that humanity has ever believed in. Some of us just go one god further.',
            'The fact that life evolved out of nearly nothing, some 10 billion years after the universe evolved out of literally nothing — is a fact so staggering that I would be mad to attempt words about it.',
        ],
    },
    {
        'id': 'hitchens',
        'name': 'Christopher Hitchens',
        'emoji': '✒️',
        'field': 'Journalism, Philosophy & Literary Criticism',
        'years': '1949 — 2011',
        'stance': 'atheist',
        'color': '#ef4444',
        'known_for': 'God Is Not Great, Letters to a Young Contrarian, debates with theologians',
        'quote': 'That which can be asserted without evidence can be dismissed without evidence. Religion is what remains when the hope of immortality collides with the fear of death.',
        'quote_source': 'God Is Not Great, 2007',
        'bio': 'Hitchens was the sharpest intellectual weapon in modern atheism. A brilliant debater and writer, he argued that religion "poisons everything" — that it is not merely wrong but actively harmful. "God Is Not Great" is one of the definitive atheist texts of the 21st century. He coined "Hitchens\'s razor" — one of the most useful tools in critical thinking.',
        'tags': ['Philosophy', 'Atheism', 'Writer'],
        'extra_quotes': [
            'Religion is violent, irrational, intolerant, allied to racism and tribalism and bigotry, invested in ignorance and hostile to free inquiry.',
            'Human decency is not derived from religion. It precedes it.',
            'The only position that leaves me with no cognitive dissonance is atheism. It is not a creed.',
        ],
    },
    {
        'id': 'russell',
        'name': 'Bertrand Russell',
        'emoji': '📐',
        'field': 'Mathematics, Logic & Philosophy',
        'years': '1872 — 1970',
        'stance': 'atheist',
        'color': '#a855f7',
        'known_for': 'Principia Mathematica, Why I Am Not a Christian, Nobel Prize 1950',
        'quote': 'The whole problem with the world is that fools and fanatics are always so certain of themselves, and wiser people so full of doubts. I would never die for my beliefs — because I might be wrong.',
        'quote_source': 'Various writings',
        'bio': 'One of the 20th century\'s greatest philosophers and mathematicians, Russell was a lifelong atheist and humanist who wrote extensively on why religion is false, harmful, and intellectually beneath serious people. His essay "Why I Am Not a Christian" (1927) remains one of the most devastating critiques of Christianity ever written.',
        'tags': ['Mathematics', 'Philosophy', 'Nobel Laureate'],
        'extra_quotes': [
            'Religion is based, I think, primarily and mainly upon fear. It is partly the terror of the unknown and partly the wish to feel that you have a kind of elder brother who will stand by you in all your troubles.',
            'The good life is one inspired by love and guided by knowledge.',
            'Men are born ignorant, not stupid. They are made stupid by education.',
        ],
    },
    {
        'id': 'darwin',
        'name': 'Charles Darwin',
        'emoji': '🦕',
        'field': 'Natural History & Evolutionary Biology',
        'years': '1809 — 1882',
        'stance': 'agnostic',
        'color': '#22c55e',
        'known_for': 'On the Origin of Species, theory of natural selection, The Descent of Man',
        'quote': 'I cannot persuade myself that a beneficent and omnipotent God would have designedly created the Ichneumonidae with the express intention of their feeding within the living bodies of caterpillars. The more I think the more I get into a muddle.',
        'quote_source': 'Letter to Asa Gray, 1860',
        'bio': 'Darwin\'s discovery of evolution by natural selection was the most intellectually shattering event in the history of science. It removed the need for a designer in biology — the one domain where God seemed most needed. Darwin became increasingly agnostic as he aged, writing that "the mystery of the beginning of all things is insoluble by us."',
        'tags': ['Biology', 'Evolution', 'Agnostic'],
        'extra_quotes': [
            'I am not apt to follow blindly the lead of other men.',
            'Ignorance more frequently begets confidence than does knowledge.',
            'It is not the strongest of the species that survives, nor the most intelligent; it is the one most adaptable to change.',
        ],
    },
    {
        'id': 'tyson',
        'name': 'Neil deGrasse Tyson',
        'emoji': '🌠',
        'field': 'Astrophysics & Science Communication',
        'years': '1958 — present',
        'stance': 'agnostic',
        'color': '#00d4ff',
        'known_for': 'Cosmos: A Spacetime Odyssey, StarTalk, Astrophysics for People in a Hurry',
        'quote': 'The universe is under no obligation to make sense to you. God is an ever-receding pocket of scientific ignorance that gets smaller and smaller as time goes on.',
        'quote_source': 'Various interviews',
        'bio': 'America\'s most recognisable astrophysicist and science communicator, Tyson refuses the label "atheist" but openly argues against religious interference in science. He calls himself "agnostic" and notes that the God of the gaps retreats with every scientific advance. His Cosmos revival brought Carl Sagan\'s vision to a new generation.',
        'tags': ['Astrophysics', 'Agnostic', 'Science Communication'],
        'extra_quotes': [
            'Curious that we spend more time congratulating people who have succeeded than encouraging people who have not.',
            'The good thing about science is that it\'s true whether or not you believe in it.',
            'We are stardust brought to life, then empowered by the universe to figure itself out.',
        ],
    },
    {
        'id': 'weinberg',
        'name': 'Steven Weinberg',
        'emoji': '⚗️',
        'field': 'Theoretical Physics & Particle Physics',
        'years': '1933 — 2021',
        'stance': 'atheist',
        'color': '#ef4444',
        'known_for': 'Electroweak unification, The First Three Minutes, Nobel Prize 1979',
        'quote': 'With or without religion, good people can behave well and bad people can do evil; but for good people to do evil — that takes religion.',
        'quote_source': 'A Designer Universe?, 1999',
        'bio': 'Nobel laureate Weinberg unified the electromagnetic and weak nuclear forces — one of the greatest achievements in physics. He was a forceful atheist who argued that religion is not just wrong but actively harmful. His statement about good people doing evil is one of the most quoted lines in modern atheism.',
        'tags': ['Physics', 'Nobel Laureate', 'Atheism'],
        'extra_quotes': [
            'The more the universe seems comprehensible, the more it also seems pointless.',
            'Religious people have grappled with the problem of evil for millennia. Science has made it worse.',
            'Science does not make it impossible to believe in God. It just makes it possible not to.',
        ],
    },
    {
        'id': 'crick',
        'name': 'Francis Crick',
        'emoji': '🔬',
        'field': 'Molecular Biology & Neuroscience',
        'years': '1916 — 2004',
        'stance': 'atheist',
        'color': '#22c55e',
        'known_for': 'DNA double helix structure, genetic code, neural correlates of consciousness, Nobel Prize 1962',
        'quote': 'Your joys and your sorrows, your memories and your ambitions, your sense of personal identity and free will, are in fact no more than the behaviour of a vast assembly of nerve cells and their associated molecules.',
        'quote_source': 'The Astonishing Hypothesis, 1994',
        'bio': 'Co-discoverer of the DNA double helix — arguably the most important discovery in the history of biology — Crick was a committed atheist who saw his work as directly contradicting religious claims about life and the soul. His "Astonishing Hypothesis" applied the same reductionist framework to consciousness, arguing the mind is entirely physical.',
        'tags': ['Biology', 'DNA', 'Nobel Laureate'],
        'extra_quotes': [
            'If you want to understand function, study structure.',
            'Christianity may be OK between consenting adults in private but should not be taught to young children.',
            'The ultimate aim of the modern movement in biology is to explain all biology in terms of physics and chemistry.',
        ],
    },
    {
        'id': 'higgs',
        'name': 'Peter Higgs',
        'emoji': '🌀',
        'field': 'Theoretical Physics & Particle Physics',
        'years': '1929 — 2024',
        'stance': 'atheist',
        'color': '#a855f7',
        'known_for': 'Higgs boson / "God particle", Higgs mechanism, Nobel Prize 2013',
        'quote': 'I\'m not a religious person. I\'m an atheist. I\'m rather non-believer. The nickname "God particle" for the Higgs boson was given by a publisher — I hate it.',
        'quote_source': 'Various interviews',
        'bio': 'The physicist who predicted the Higgs boson — the particle that gives matter its mass — was an atheist who hated the media nickname "God particle." He felt it was misleading and theologically absurd. Higgs criticised Richard Dawkins for being too aggressive toward religion, but was clear about his own atheism.',
        'tags': ['Physics', 'Nobel Laureate', 'Particle Physics'],
        'extra_quotes': [
            'The Higgs boson has nothing to do with God. It is simply the particle that explains mass.',
            'I have no time for religion. I find it quite extraordinary that a sophisticated human being would believe in a personal God.',
        ],
    },
    {
        'id': 'atkins',
        'name': 'Peter Atkins',
        'emoji': '🧪',
        'field': 'Physical Chemistry',
        'years': '1940 — present',
        'stance': 'atheist',
        'color': '#f97316',
        'known_for': 'Physical Chemistry textbook, On Being, science vs religion debates',
        'quote': 'Science is the only path to understanding reality. Religion is fantasy dressed up as comfort. The universe has no purpose, no compassion, and no obligation to care about us — and that is beautiful.',
        'quote_source': 'On Being, 2011',
        'bio': 'Oxford chemist Peter Atkins is one of the most outspoken scientific atheists. He argues there is no place for God anywhere in a scientific understanding of the universe, and that the attempt to reconcile religion and science is intellectually dishonest. His debate performances against William Lane Craig are notable for their bluntness.',
        'tags': ['Chemistry', 'Atheism', 'Oxford'],
        'extra_quotes': [
            'Science has never failed to explain anything it has turned its attention to.',
            'Compromise between science and religion is not possible. One is true and the other is not.',
        ],
    },
    {
        'id': 'stenger',
        'name': 'Victor Stenger',
        'emoji': '♾️',
        'field': 'Particle Physics & Cosmology',
        'years': '1935 — 2014',
        'stance': 'atheist',
        'color': '#ef4444',
        'known_for': 'God: The Failed Hypothesis, MonkeyGod simulations, the maximum-entropy origin argument',
        'quote': 'The universe looks exactly the way it would be expected to look if there were no creator.',
        'quote_source': 'God: The Failed Hypothesis, 2007',
        'bio': 'A particle physicist who worked on the discovery of the Upsilon particle and the W boson before turning to a rigorous, quantitative critique of theism. Stenger treated "God exists" as a scientific hypothesis and tested it against cosmological data, arguing the universe\'s entropy, symmetry, and physical constants are exactly what undirected physics predicts. His MonkeyGod computer simulations randomized fundamental constants and still produced star-forming universes in roughly half of all trials.',
        'tags': ['Physics', 'Cosmology', 'Fine-Tuning', 'Atheism'],
        'extra_quotes': [
            'The entropy of the universe at the start was, in fact, as large as it could be for a universe of that size — so even God wasn\'t given any information to work with.',
            'No evidence of purpose in the universe has ever been found. The hypothesis of God adds nothing to our understanding and explains nothing that physics does not already explain.',
            'If physicists running random simulations of universes can produce stars and galaxies even when wildly varying the constants of nature, then the "fine-tuning" argument is far weaker than its proponents claim.',
        ],
    },
    {
        'id': 'dennett',
        'name': 'Daniel Dennett',
        'emoji': '🧩',
        'field': 'Philosophy of Mind & Cognitive Science',
        'years': '1942 — 2024',
        'stance': 'atheist',
        'color': '#00d4ff',
        'known_for': 'Consciousness Explained, Breaking the Spell, compatibilist free will, one of the "Four Horsemen" of New Atheism',
        'quote': 'Religion is a natural phenomenon, and like all natural phenomena, it can — and should — be studied scientifically, not taken on faith.',
        'quote_source': 'Breaking the Spell, 2006',
        'bio': 'A philosopher who treated both consciousness and religion as natural phenomena to be explained by science rather than mysteries beyond its reach. His "Breaking the Spell" applied evolutionary and cognitive science to explain why religious belief is so widespread, without assuming any of it is true. He defended a compatibilist account of free will grounded entirely in physical causation, with no need for a soul.',
        'tags': ['Philosophy', 'Cognitive Science', 'New Atheism'],
        'extra_quotes': [
            'There\'s nothing I like less than bad arguments for a view I hold dear.',
            'I love the way the religions have developed but I think they\'re wrong on a number of points, and, moreover, I think they\'re dangerous, generally, in a more important way than they\'ve ever been before.',
            'The secret to happiness is: Find something more important than you are and dedicate your life to it.',
        ],
    },
    {
        'id': 'harris',
        'name': 'Sam Harris',
        'emoji': '🎯',
        'field': 'Neuroscience & Philosophy',
        'years': '1967 — present',
        'stance': 'atheist',
        'color': '#fbbf24',
        'known_for': 'The End of Faith, Free Will, secular ethics grounded in well-being',
        'quote': 'The greatest problem confronting civilization is not merely religious extremism: rather, it is the larger set of cultural and intellectual accommodations we have made to religious faith itself.',
        'quote_source': 'The End of Faith, 2004',
        'bio': 'A neuroscientist who argues that morality does not require religion — it can and should be grounded in reducing suffering and increasing well-being, principles that are empirically investigable. His book "Free Will" argues neuroscience is incompatible with the libertarian, soul-driven free will required by most religious doctrines of judgment and sin.',
        'tags': ['Neuroscience', 'Philosophy', 'Secular Ethics', 'New Atheism'],
        'extra_quotes': [
            'Free will is an illusion so convincing that people simply refuse to believe that we don\'t have it.',
            'Science must destroy religion. There is no other way around it: every religion makes claims about the way the world is, and these claims can be in conflict with scientific knowledge.',
            'We don\'t have to respect bad ideas just because people sincerely believe them.',
        ],
    },
    {
        'id': 'hossenfelder',
        'name': 'Sabine Hossenfelder',
        'emoji': '🔬',
        'field': 'Theoretical Physics',
        'years': '1976 — present',
        'stance': 'atheist',
        'color': '#a855f7',
        'known_for': 'Lost in Math, science communication, criticism of untestable physics, superdeterminism research',
        'quote': 'The universe doesn\'t care what we believe. It just is what it is, and our job is to find out — carefully, skeptically, and without wishful thinking.',
        'quote_source': 'Lost in Math, 2018',
        'bio': 'A theoretical physicist and prominent science communicator known for rigorous skepticism — applied as readily to untestable physics speculation as to religious claims. She argues that both string theory\'s untestable elements and theological claims share the same flaw: appealing to beauty, intuition, or tradition instead of evidence. Her YouTube channel reaches millions with plain-spoken explanations of physics and pushback against pseudoscience.',
        'tags': ['Physics', 'Science Communication', 'Skepticism'],
        'extra_quotes': [
            'A theory that is not predictive is not a scientific theory, no matter how beautiful its mathematics.',
            'I am very skeptical of grand claims that are not backed up by data — whether they come from physicists or from priests.',
        ],
    },
    {
        'id': 'turing',
        'name': 'Alan Turing',
        'emoji': '💻',
        'field': 'Mathematics & Computer Science',
        'years': '1912 — 1954',
        'stance': 'atheist',
        'color': '#06b6d4',
        'known_for': 'Turing machine, codebreaking at Bletchley Park, the Turing Test, foundations of computer science',
        'quote': 'I am not interested in developing a powerful brain. All I am after is just a mediocre brain, something like the President of the American Telephone and Telegraph Company.',
        'quote_source': 'Various — note: Turing\'s recorded religious views came primarily via his Cambridge friend and biographer accounts',
        'bio': 'The father of theoretical computer science and the codebreaker whose work at Bletchley Park is credited with shortening WWII by years, Turing was raised Christian but became an atheist as a young man after the death of his close friend Christopher Morcom, finding no comfort or coherence in promises of an afterlife. He went on to lay the mathematical foundations of computation and ask, in "Computing Machinery and Intelligence" (1950), whether machines could think — treating mind as a process to be investigated, not a divine spark.',
        'tags': ['Mathematics', 'Computer Science', 'Codebreaking'],
        'extra_quotes': [
            'Science is a differential equation. Religion is a boundary condition.',
        ],
    },
    {
        'id': 'blackmore',
        'name': 'Susan Blackmore',
        'emoji': '🌀',
        'field': 'Psychology & Cognitive Science',
        'years': '1951 — present',
        'stance': 'atheist',
        'color': '#f97316',
        'known_for': 'The Meme Machine, research debunking near-death and out-of-body experiences as brain phenomena',
        'quote': 'I spent thirty years trying to find evidence for the paranormal and psychic phenomena. I found nothing — and that absence of evidence, after looking so hard, is itself powerful evidence.',
        'quote_source': 'Various interviews and "Seeing Myself", 2017',
        'bio': 'Blackmore began her career as a parapsychologist actively trying to find scientific evidence for psychic phenomena, out-of-body experiences, and life after death. Decades of rigorous experiments turned up nothing — and she became one of the most credible skeptical voices precisely because she started as a believer. Her research reproduced near-death and out-of-body experiences using brain stimulation and altered states, showing them to be neurological, not spiritual.',
        'tags': ['Psychology', 'Skepticism', 'Near-Death Experiences'],
        'extra_quotes': [
            'Out-of-body experiences can be reliably triggered by stimulating the temporoparietal junction — they are a glitch in the brain\'s body model, not evidence of a soul leaving the body.',
            'I no longer believe that life after death is even a sensible question to ask, given what we now know about the brain.',
        ],
    },
]
